### ISSUE TITLE
feature: group names

### ISSUE THREAD

**Issue by cppcooper** [asamuzaK/sidebarTabs#101]
I think, this would be reserved for when the groups are collapsed but perhaps all the time. I just personally would find it useful when they are collapsed so that I can not need to remember what tabs are with which first tab, which is fine default behaviour since it is easy and quick for temporary groups.
For your consideration.
Cheers

**Comment by asamuzaK** [comment]
I considered those needs at the early development stage of this extension and decided not to implement such a feature.
The reason for this is, in this extension the grouping is only temporary, so I decided that no more than color-coding is needed to identify each group.
If I change that now, it will require a total rewrite of the code and that I don't want to do.

**Comment by cppcooper** [comment]
Oh I see, I am using it against the intended use case then. It is very handy for compressing categories of open links. eg. projects/research

**Comment by asamuzaK** [comment]
If you want to search for a specific tab, enter some keywords in the URL bar and check for the item with "Switch to Tab".
You don't have to remember the first tab at all.

**Comment by asamuzaK** [comment]
Accepted as a feature request, but please do not expect it to be implemented in the near future as it will require a fairly major change.

Things to consider for adding label to tab groups.

* Controlling Labels
  * When and how to display
  * Shadow DOM
    Not required, but for future management it is better to switch to Shadow DOM.
* Appearance of the label
  * How to distinguish between label and tabs
  * Initial value of the label
  * Where to place the edit button

**Comment by asamuzaK** [comment]
Mock

HTML:
```
<section class="tab-container">
  <h1 class="tab-container-heading" hidden>
    <span class="container-label"></span>
    <button class="container-label-edit">
      <img class="container-label-edit-icon" />
    </button>
  </h1>
  <div class="tab"></div>
  <div class="tab"></div>
</section>
```

* `.tab-container-heading`: hidden by default
  * show / hide status of heading is independent for each group
    for example, groupA shows heading, groupB hidden, groupC shown...
  * show / hide status will only be controlled from context menu
    * TODO: is that really be okay?
  * hide heading when group is ungrouped
* add context menu item `Tab Group > Show Group Label`
  * prepare toggle title `Hide Group Label` for the  case when heading is shown
  * disable or hide menu item if tab is not grouped
* when menu item `Show Group Label` is clicked
  * show `.tab-container-heading` (remove `hidden` attr)
  * synthetic click `.tab-container-label-edit`
  * toggle title of menu item to `Hide Group Label`
* when `.tab-container-label-edit` is clicked
  * set `contenteditable="true"` attr to `.tab-container-label`
    * TODO:
      * when to remove `contenteditable` attr
        by `Enter` key?, `input` event?
      * how and where to save edited value
        only in session store will be okay?

**Comment by asamuzaK** [comment]
Appearance

![folder_light](https://user-images.githubusercontent.com/6790339/83342378-c8702200-a329-11ea-9125-885b88c372ac.png)

![folder_dark](https://user-images.githubusercontent.com/6790339/83342381-cb6b1280-a329-11ea-929e-539e8ebf9a1a.png)

**Comment by cppcooper** [comment]
Wow that was a fast turn around. You must love working on this project =)

**Comment by asamuzaK** [comment]
Try build:
[sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by cppcooper** [comment]
Seems to work without any issue. If anything pops out, I'll fill you in.
