### ISSUE TITLE
Closing tab with middle mouse click activates fast roller feature.

### ISSUE THREAD

**Issue by solowav3** [asamuzaK/sidebarTabs#111]
This behavior happens when the number of tabs exceeds visual height of the window.

![Tabs middle click issue preview](https://media.giphy.com/media/0xwhKctVNyQIcpwHAU/giphy.gif)

**Comment by asamuzaK** [comment]
Confirmed.
Thanks for catching this.

**Comment by asamuzaK** [comment]
Released v3.7.3

**Comment by solowav3** [comment]
Thanks for an awesome extension and blazing fast fix, cheers!
