### ISSUE TITLE
CTRL + W doesn't close pinned tab

### ISSUE THREAD

**Issue by solowav3** [asamuzaK/sidebarTabs#112]
Pretty much summed in the title. Right-click -> close & mouse-wheel click on the pinned tab closes as expected, CTRL + W doesn't :)

**Comment by asamuzaK** [comment]
Firefox is designed to work that way.
https://support.mozilla.org/en-US/questions/1279090
https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open

**Comment by solowav3** [comment]
Oh I see, thanks for clarification and sorry for the confusion.

So, I suppose it closes the "issue".

**Comment by asamuzaK** [comment]
no worries
