### ISSUE TITLE
Extension hangs for several seconds when tab state changes with many tabs

### ISSUE THREAD

**Issue by ntninja** [asamuzaK/sidebarTabs#127]
I just discovered your vertical tabs extension and I like the idea of just having exactly single level of groups (unlike Tree Style Tabs or Vertical Tabs Reloaded) and your implementation of the idea is pretty solid too!

Sadly, I found your extension to be basically unusable in my case since it seems to be overwhelmed with my ~1000 tabs currently open. Any action modifying the tabs state (opening tab, closing tab, switching tab, assigning tab to group, …) causes the extension's sidebar to become unresponsive for several seconds. Making the extension arduous to use at best.

**Comment by asamuzaK** [comment]
Is it an issue only with this extension?
Or is there a similar one with Tree Style Tabs,  Vertical Tabs Reloaded, etc.?

**Comment by ntninja** [comment]
It's not an issue with Vertical Tabs Reloaded (that's the extension I'm coming from actually). If I remember correctly, this used to be an issue a couple of years ago, before they optimized it. Since I've been using VTR since basically since its inception (I needed a replacement for XUL/XPCOM VT with the Firefox WebExtension transition), this must have happened around 2018, I think.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/session/dest)
See if it works or not.

**Comment by asamuzaK** [comment]
Updated [try build](https://github.com/asamuzaK/sidebarTabs/tree/session/dest)
See if it works or not.

**Comment by ntninja** [comment]
Thank you! I've tried your modified version and it reduces the average freeze time from about ~7s to ~2s. So still there, but much more manageable!
