### ISSUE TITLE
Scroll SideBAr Tabs

### ISSUE THREAD

**Issue by bussness12** [asamuzaK/sidebarTabs#128]
PLEASE can you make it so we can Scroll through the tabs when our mouse is hovered over the Sidebar Tab and we scroll? Please I would go to Japan and..worship you and build the shrine, this add-on would get MEGA popular fast if you did that...!

**Comment by asamuzaK** [comment]
Open options page and enable` Switch tab by scrolling mouse wheel`

**Comment by bussness12** [comment]
Thanks, you are god!! Also, is there a shortcut like ctrl+a for example to open/pull up the sidetab instead of clicking the extension near the toolbar, if not, could you implement that in a future release? 

thanks for the add-on :) i'll be in japan soon..

**Comment by asamuzaK** [comment]
Please don't ask different questions one after another in one issue.

> Also, is there a shortcut like ctrl+a for example to open/close the sidetab instead of clicking the extension near the toolbar, if not, could you implement that in a future release?

See [Manage extension shortcuts in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)

Look for `Sidebar Tabs` and  set your shortcut key for `Toggle open/close state`.

> also if can set to the bottom of the screen in addition to the left and right options you already put would be cool

Not possible. No API for that.
