### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by cppcooper** [asamuzaK/sidebarTabs#132]
I have no idea where or under what precise conditions the threshold is passed. But it seems if a window with a lot of tabs is closed, or subsequently re-opened the memory consumption just keeps stepping up until swap is reached.. and then a while after that. My best guess is that it is something tied to creating each of the tabs. Then a new allocation is obtained, perhaps not for each tab.. but only after X tabs because the number of memory steps doesn't seem to correspond to the number of tabs (not precisely anyway). I haven't done too much testing, just enough to isolate this plugin as the source.

Of course the steps I see in the memory monitor could just be a quirk of the OS or firefox, or the monitor itself.

**Comment by asamuzaK** [comment]
I changed how to save sessions in current version v4.2.0.

Did this issue occur in previous versions as well?
Is it possible to temporarily install v4.1.0 and test with it?
[Sidebar Tabs version history](https://addons.mozilla.org/en-US/firefox/addon/sidebartabs/versions/)

**Comment by cppcooper** [comment]
It did not happen in previous version as far as I know. It is a new experience, I think I remember a lag being introduced in loading windows with a lot of tabs but I don't recall when that happened with hindsight it was probably memory leaking.

I spent 10 minutes loading my tabs 100 regular tabs into power tabs plugin groups roughly the same time I opened this issue. It has some benefits (custom colouring, easier sorting, domain filtering) but it also has some down sides (like dragging tabs being weird, poor ui sizing).

Anyways, I'll probably stick to this for the foreseeable future as it would be more time consuming to be dealing with memory leaks. Hope you can figure out a test scenario and how to resolve it.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/port/dest)
Do you see any improvement?

**Comment by asamuzaK** [comment]
Please give a feedback.
I can't go any further.

**Comment by asamuzaK** [comment]
No response yet, I am going to merge the current PR.

If you're experiencing a memory leak, I think it's because you can't exchange messages with the background when you close the sidebar or close the window.
In current PR, I've changed to connection-based messaging to make this problem less likely to occur, in theory.

If you still have problems, feel free to reopen.
