### ISSUE TITLE
Improve dark theme

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#154]
Hi, Please Improve the dark theme.
Icons are displayed in black.
![image](https://user-images.githubusercontent.com/23485114/149640098-353f7722-9942-4043-80ca-1d742e1daaf4.png)

**Comment by asamuzaK** [comment]
From `about:config`, set  `svg.context-properties.content.enabled` to `true`.

**Comment by xmha97** [comment]
Thanks.
