### ISSUE TITLE
Support text drag and drop

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#155]
Hi,
Please support text drag and drop.
Like original firefox tabs
![image](https://user-images.githubusercontent.com/23485114/149702576-2b75d098-fe32-4be1-a7fd-f13d58eb3e38.png)
Thanks.

**Comment by asamuzaK** [comment]
[try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Tell me if it works as expected.

**Comment by xmha97** [comment]
Thank you <3
