### ISSUE TITLE
New tab button

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#156]
Hi @asamuzaK 
The new tab button makes 2 new tabs sometimes.

https://user-images.githubusercontent.com/23485114/150524564-02493346-c5a0-4e1f-a670-8e50a80cd996.mp4

(I only click once)

**Comment by asamuzaK** [comment]
I need a exact step to reproduce.

**Comment by xmha97** [comment]
I just click the add button but two pages are created.
Of course, this does not always happen, only sometimes.
You can connect to my laptop using AnyDesk.

**Comment by xmha97** [comment]
It seems that this issue was fixed on v7.0.0a1.
Thanks.

**Comment by xmha97** [comment]
Ok, thank you for your support.
