### ISSUE TITLE
Reverse scroll

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#158]
![image](https://user-images.githubusercontent.com/23485114/150597806-05d35d7a-e747-4ca6-bbe3-7b93cf65b696.png)

Please add an option for the reverse scroll.
My laptop touchpad scroll working reverse.

**Comment by asamuzaK** [comment]
[try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by xmha97** [comment]
> [try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Thanks.
