### ISSUE TITLE
Can't show "Sidebar Tabs" on the private window by default

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#160]
Hi,
Can't show "Sidebar Tabs" on the private window by default.

![Firefox](https://user-images.githubusercontent.com/23485114/150628734-1561c658-9030-49cb-9ee1-41fe32b9dc0b.png)

**Comment by asamuzaK** [comment]
See [Extensions in Private Browsing | Firefox Help](https://support.mozilla.org/en-US/kb/extensions-private-browsing)

**Comment by MasterKia** [comment]
I have allowed the add-on to work in private windows but I face another problem:

When I open a private window, the Sidebar tabs are closed and I have to manually open it by clicking on the add-on icon in the toolbar. Can this be fixed?

**Comment by MasterKia** [comment]
I also have " Allow extension to read and modify browser settings " enabled, if that matters.
