### ISSUE TITLE
Improve Drag and Drop

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#162]
✔️ Drag and drop working when I drag a text to a tab:
![image](https://user-images.githubusercontent.com/23485114/150773965-10227b99-75f0-4534-ae72-aac22385f498.png)
❌ But when drag a text to sidebar free space, search does working:
![image](https://user-images.githubusercontent.com/23485114/150773639-bda0cd36-832e-440d-a8be-da9c8f858aa0.png)

**Comment by asamuzaK** [comment]
[try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by xmha97** [comment]
Now I can't drag to free space:
![image](https://user-images.githubusercontent.com/23485114/150943430-daa23637-238e-4d7d-9644-226eb2aa01c8.png)
I need the Firefox tab bar behavior:
![image](https://user-images.githubusercontent.com/23485114/150943787-77c312c0-38e8-402e-92f8-7849a8bf890c.png)

**Comment by asamuzaK** [comment]
[try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Tell me if it's working as expected.

**Comment by xmha97** [comment]
Thanks.
