### ISSUE TITLE
Keep customized values for each theme

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#169]
# Summary
Add an option to use toolbar background for sidebar background.

❌ Actual Behavior
![image](https://user-images.githubusercontent.com/23485114/151681029-3d520366-360d-4696-9ac5-85f8ad682875.png)

✔️ Expected Behavior
![image](https://user-images.githubusercontent.com/23485114/151681017-ce1708e7-a395-48bc-9933-dab1688e0ef1.png)

**Comment by asamuzaK** [comment]
You can already do that from  `Custom Theme`.
Why do we need this new option?

**Comment by xmha97** [comment]
At first glance `Custom Theme` is good:

![image](https://user-images.githubusercontent.com/23485114/152443119-515b3ad6-a0aa-46ab-a3be-ad06a86bca21.png)

But my OS theme changes to dark and light with sunrise and sunset,
I need both Dark and Light themes.
On the other hand, the colors of the texts are disturbed:

![image](https://user-images.githubusercontent.com/23485114/152442798-bc0b3156-c1a4-4a16-8f33-758479141982.png)

**Comment by asamuzaK** [comment]
I see.
So it's not just about the background color, you need to keep the values customized for each theme, right?
Looks like it will need a major fix, but it's worth implementing.

**Comment by xmha97** [comment]
Thanks, please publish a version on:
https://github.com/asamuzaK/sidebarTabs/tree/master/dest
