### ISSUE TITLE
Add an option to always show group label

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#171]
Please add an option to always show group label
![image](https://user-images.githubusercontent.com/23485114/151925835-423060b2-3fd0-4b18-81ec-0d4b3ebc12b9.png)

![image](https://user-images.githubusercontent.com/23485114/151926188-3955d1b5-5c22-4099-b6d3-317ceaa22e17.png)

**Comment by asamuzaK** [comment]
It's by design.
If you implement this feature, you'll need to take the user's focus and move it to the label.

See also [feature: group names · Issue #101 · asamuzaK/sidebarTabs](https://github.com/asamuzaK/sidebarTabs/issues/101)
