### ISSUE TITLE
Add the mute button for tab groups

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#177]
Please add the mute button for tab groups
![image](https://user-images.githubusercontent.com/23485114/153004975-c7d9fca1-0316-4446-9c54-8e4497684e29.png)

**Comment by asamuzaK** [comment]
I understand what you want to achieve with this, but it doesn't seem useful.

For example, if one tab is muted and another tab is unmuted in the same group, should the group label show the mute or unmute button?

In Firefox, if you press the button of a tab that has a mute button, for example, from among multiple selected tabs, all the remaining selected tabs will also be muted.
It has already been implemented in the sidebarTabs.
Isn't that enough?

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/153133504-9844efdc-0e09-4816-a3e5-81c863a09b26.png)
OK, Thanks.
