### ISSUE TITLE
Allow ungrouping pinned tabs or exclude them from auto collapse 

### ISSUE THREAD

**Issue by evrenesat** [asamuzaK/sidebarTabs#180]
Thank you for this extension with a feature set at the level you would expect from browser itself, nothing less or more!

But I have a small issue with auto-collapsing of pinned tabs. Generally I only use a few pinned tabs and prefer having them always visible. It would it be very nice if pinned tabs could be excluded from auto-collapsing or if we could ungroup them.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by evrenesat** [comment]
Thank you very much, that's perfect.
