### ISSUE TITLE
Hiding the close button

### ISSUE THREAD

**Issue by char101** [asamuzaK/sidebarTabs#183]
Hi,

Is it possible to hide the close button on each tabbar items?

I want to make a favicon only vertical tabs and prefer to have the close buttons removed to prevent accidentally closing the tab when clicking it.

![2022-03-25 10_16_16-Add-ons Manager — Mozilla Firefox](https://user-images.githubusercontent.com/71255/160047416-090513b2-6155-43d5-b773-e90d3b7f94f9.png)

**Comment by asamuzaK** [comment]
How about trying [ranmaru22/firefox-vertical-tabs: Vertical tabs for Firefox, inspired by Edge.](https://github.com/ranmaru22/firefox-vertical-tabs)

**Comment by char101** [comment]
It is just a stylesheet that make Firefox looks like Edge. The actual vertical tabs is due to the **Tab Center Reborn** addon (as written in the installation steps). For me the addon requires too many permissions. I prefer addon with minimal permissions.

**Comment by char101** [comment]
How about addon a media filter to this addon css? When the document (sidebar) width is less than e.g. 100px, then the close button should be hidden.

![2022-03-25 17_19_45-Toolbox - Extension _ Sidebar Tabs — Mozilla Firefox](https://user-images.githubusercontent.com/71255/160102482-c310f67f-262f-486c-aeea-ada04fc7d993.png)

**Comment by asamuzaK** [comment]
Ah, adding media query makes sense.

**Comment by asamuzaK** [comment]
[try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
Added new option to use user CSS.
Try it out and send me your feedback.

**Comment by char101** [comment]
Thanks, I can confirm it works.

**Comment by jt3k** [comment]
you can simply add a custom style sheet to only show the close button on the tab that the mouse is hovering over

```css
:not(:hover) > .tab-close {
	display: none;
}
```

**Comment by sith-on-mars** [comment]
> you can simply add a custom style sheet to only show the close button on the tab that the mouse is hovering over
> 
> ```css
> :not(:hover) > .tab-close {
> 	display: none;
> }
> ```

Works perfectly thanks. This should be included by default.
