### ISSUE TITLE
Option to disable Close-on-Middle-Click

### ISSUE THREAD

**Issue by hurzl** [asamuzaK/sidebarTabs#185]
Would that be possible?

**Comment by asamuzaK** [comment]
Why you need to disable?

See also: [1439247 - Request an option to disable &quot;close tab with middle click&quot; feature](https://bugzilla.mozilla.org/show_bug.cgi?id=1439247)

**Comment by hurzl** [comment]
Because I scroll via middle-button (laptop) and sometimes tabs disappear ...

**Comment by asamuzaK** [comment]
I see.

**Comment by hurzl** [comment]
Thanks! (I didn't expect it to need that much code ...)

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
