### ISSUE TITLE
[Question][Feature request] Is it possible to close all tabs in a group?

### ISSUE THREAD

**Issue by waltergallegog** [asamuzaK/sidebarTabs#186]
I think it would be very helpful to have the possibility to close all the tabs in a group. Is this currently possible?
Perhaps by some keybinding like holding shift+mouse middle button click, or a new entry in the right click menu.

Motivation for the request: 
 - you are searching for something and have opened a bunch of tabs related to the search (google, stackoverflow, other forums etc). 
 -  All of these tabs are automatically grouped together (fantastic feature btw). 
 - You finally find what you needed, and now you don't need all of those opened tabs in the group anymore. Having a way to close all of them at once would be superb.

Thanks.

PS: By close I don't mean collapse, actually close all the tabs in the group.

**Comment by asamuzaK** [comment]
You can of course add it as a new item to the context menu, but you need to decide where to put it.

```
Tab Group > Close Tab Group
```
or
```
Close Multiple Tabs > Close Tab Group
```

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by waltergallegog** [comment]
Tried it and it works, thanks!
