### ISSUE TITLE
Only first link opened with middle click is added to tab group

### ISSUE THREAD

**Issue by waltergallegog** [asamuzaK/sidebarTabs#189]
Hi,
I'm not sure if this is a bug or the intended behavior, but I thought it would be useful to report it anyway.

Scenario: 
You are searching the web for a solution to a problem, and open multiple tabs related to the issue.

Steps to reproduce:
- Open your favorite search engine and search for what you want.
 - Click on the first 5 results with the mouse middle click, so the links are opened in new tabs.

**Expected behavior:**
 The opened tabs are all added to the search engine group.

**Observed behavior:**
 Only the first tab is added to the search engine group.

Here a screenshot of what I mean. As you can see, only the first link was added to the group:
![image](https://user-images.githubusercontent.com/5270762/164720033-fb4b3177-023e-4f0a-b5c3-13b9cb0956f4.png)

**Comment by waltergallegog** [comment]
I just found out that after enabling the option "Always put the newly opened grouped tab at the end of the group", it works as expected, all tabs are added to the group.

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
