### ISSUE TITLE
Collapse/Expand shouldn't switch to tab

### ISSUE THREAD

**Issue by hurzl** [asamuzaK/sidebarTabs#197]
When I click to collapse a group, the first tab is shown (and loaded), which isn't necessary.

**Comment by asamuzaK** [comment]
It was designed to work that way, but what is wrong with that behavior?

**Comment by hurzl** [comment]
When I want to collapse a group, I usually don't want to see it right now and reload all of its contents etc.

**Comment by asamuzaK** [comment]
I see.
So, I think I will change the behavior of collapsing a tab group to activate the first tab if there are active tabs in the group, and not activate it if there are no active tabs.
What do you think about this change?

**Comment by hurzl** [comment]
Sounds reasonable. If it is the currently active group it makes sense to switch to the first tab on collapse.

**Comment by hurzl** [comment]
... and also on expanding a group, I don't necessarily want to see the first tab but choose by myself ...

**Comment by asamuzaK** [comment]
That request is not worth considering.

**Comment by hurzl** [comment]
... and so you didn't.

**Comment by asamuzaK** [comment]
I took it to mean that you wanted to allow the user to choose which tab gets focus (e.g., always focus on the last tab instead of the first in the group), but I may not have understood what you were saying correctly.

The new implementation does not focus on the first tab when expanding an inactive collapsed tab.

**Comment by asamuzaK** [comment]
Check v7.3.3

**Comment by hurzl** [comment]
Oh I see ... I just meant to not focus on any tab automatically on expand also. I didn't have the newest implementation because firefox only just now updated it. The behavior in 7.3.3 is just perfect already ...
