### ISSUE TITLE
[Feature request] when draggin url to tab area, open it as a link directly

### ISSUE THREAD

**Issue by waltergallegog** [asamuzaK/sidebarTabs#200]
Dear dev,
The behavior when using the native firefox tabs is the following:
 1. If I drag an url to the tab area, a new tab is opened with the website of that url.
 2. If I drag a text that is not an url, a new tab is opened, and the text is used as the query for my default search engine.

The behavior when using sidebarTabs is always number 2 above.
So if I drag an url, I will get a search result of that url, instead of the url's website.

Is it possible to add an option to have the native firefox behavior?

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by waltergallegog** [comment]
Thanks for the quick fix, it works.
