### ISSUE TITLE
Can you pls add support for the "Adaptive tab bar color" extension

### ISSUE THREAD

**Issue by Hazem42** [asamuzaK/sidebarTabs#207]

**Comment by asamuzaK** [comment]
Please at least write down the references.

* [Adaptive Tab Bar Color – Get this Extension for 🦊 Firefox (en-US)](https://addons.mozilla.org/en-US/firefox/addon/adaptive-tab-bar-color/)
* [YS-Wong/Adaptive-Tab-Bar-Color: Change the color of Firefox tab bar to match the website theme](https://github.com/YS-Wong/Adaptive-Tab-Bar-Color)

**Comment by Hazem42** [comment]
I'm sorry man. mb <3

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by Hazem42** [comment]
It's works, Thank you so much.
I really appreciate your time and effort <3

**Comment by Hazem42** [comment]
It's a bit buggy and takes a couple seconds to adapt the theme

**Comment by asamuzaK** [comment]
> It's a bit buggy and takes a couple seconds to adapt the theme

This doesn't tell anything.
In more details please.

* What do you mean "buggy"? Behavior, result of colors? etc.
* Does it always take time? At a particular site? Is it reproducable? etc.

**Comment by asamuzaK** [comment]
In theory, if you move between tabs at high speed, for example by scrolling, there could be some kind of problem.

**Comment by Hazem42** [comment]
- when I activate the extension, it doesn't adapt to the theme immediately, I have to switch to a different tab (with a different domain, if I was on YouTube for example and switch to a different YouTube tab, it doesn't adapt the theme).
- some times (randomly) when switching to a different tab, it lags a bit and doesn't adapt the theme immediately (or as fast as the URL bar). and no I don't use the mouse wheel to switch tabs
- when I right click the new tab button (+), it doesn't show the context menu where I can open a new container tab.
**FYI** the previous was my experience on Linux (Linux mint). 
**ON WINDOWS**> if you open the settings for the "adaptive tab bar color" extension, you'll fine > "tab bar color offset" and "URL field color offset". the "sidebar tab" extension doesn't use the "tab bar color offset" setting, instead it uses the "URL field color offset" setting.
I'll keep you updated if I find something else.
Thank you.

**Comment by Hazem42** [comment]
> when I activate the extension, it doesn't adapt to the theme immediately, I have to switch to a different tab (with a different domain, if I was on YouTube for example and switch to a different YouTube tab, it doesn't adapt the theme).

This is fixed, but it still lags a bit to adapt the theme.

> Since the theme is applied to the sidebar asynchronously, there will be a time lag.

I installed the [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) extension to test this, and it's faster to change theme (it's almost instant), there's a noticeable performance difference.

> I can't reproduce.
Is it really related to this issue?

don't worry about this, it works now.

>If the theme has a value of 'sidebar', it will be used.
   If not, the 'frame', which is the background color of the inactive tab, is used then.

I'm not sure what u mean here, but I tested with tree style tab, and it uses the tab bar theme not the URL field theme.
If u mean that you intended this to happen, can you add the option to change it, because the side bar doesn't look good when using a theme that doesn't match the site or the URL bar.

**Comment by asamuzaK** [comment]
[3rd try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by Hazem42** [comment]
Better overall performance, but when activating the extension (like switching to if from another extension) it still doesn't adapt the theme and I still have to switch to a different tab for it to work.
when switching to a different tab, the time it takes to adapt the theme is a lot better than the previous version but it's still not almost instant like the "tree style tab" extension.

**Comment by asamuzaK** [comment]
[4th try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Rather than trying to get the redraw delay close to zero, I prioritize load reduction by throttling the processing that occurs continuously when a user switches tabs with wheel scrolling.
In my environment, redraws take about 60 to 200 milliseconds.
This value may vary depending on the environment, but I do not consider it an unacceptably long processing time.

**Comment by asamuzaK** [comment]
[Last try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

I believe this issue has been resolved fixed.
If there are still bugs or any concerns, please reopen this issue or submit a new one.

Thank you for your contribution.

**Comment by Hazem42** [comment]
It redirects me to the previous build (the 3rd build).
It's totally not unacceptably long, I just wanted it to feel smoother that's all

**Comment by Hazem42** [comment]
Thank you for your time and effort.

**Comment by asamuzaK** [comment]
Check the version.
v9.0.0a3 is the latest.

**Comment by Kamrulhasan12345** [comment]
I don't know why but I see this difference:

![sidebar_current](https://i.imgur.com/DsRkF5o.png)

![expected](https://i.imgur.com/rfi0Hj1.png)
