### ISSUE TITLE
Select multiple tabs and group them

### ISSUE THREAD

**Issue by rayman89** [asamuzaK/sidebarTabs#21]
I thik it would be nice to be able to select multiple tabs at one time to be able to group them and do all this to the selected tabs 
![imagen](https://user-images.githubusercontent.com/5449042/39015478-17b5417c-43e3-11e8-8f79-99bdc87779e8.png)

**Comment by alreadydone** [comment]
Multiple Tab Handler works with Tree Style Tab but not with any other vertical/sidebar tab addons I'm aware of.

**Comment by asamuzaK** [comment]
Lets split this issue in two.

1.  Select multiple tabs and group them
2.  Extend tab groups feature (add `Mute grouped tabs audio`, `Pin grouped tabs` and so on)

For the latter, I filed #25.

**Comment by asamuzaK** [comment]
Try build
[v0.28.0a2](https://github.com/asamuzaK/sidebarTabs/tree/master/dest "sidebarTabs/dest at master · asamuzaK/sidebarTabs")

**Comment by rayman89** [comment]
Works. Thank you.
