### ISSUE TITLE
Keyboard shortcut to hide/show tabs

### ISSUE THREAD

**Issue by KaiDevrim** [asamuzaK/sidebarTabs#210]
I would love it if there was someway to basically press the extension button but using a keyboard shortcut. Basically just use one shortcut to show and hide the tab bar.

**Comment by asamuzaK** [comment]
Ref [Manage extension shortcuts in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)

**Comment by asamuzaK** [comment]
@KaiDevrim resolved?

**Comment by asamuzaK** [comment]
No reply.
Feel free to reopen.
