### ISSUE TITLE
Links opened from the same tab are not always grouped together 

### ISSUE THREAD

**Issue by eugbyte** [asamuzaK/sidebarTabs#216]
# How to reproduce
1. Have 2 empty  ungrouped tabs
2. In the top tab, navigate to a webpage
3. Start opening the links. Make sure there is more than 1 link to be opened

Observe that:
1. The first link opened will be grouped with the original tab
2. Subsequent tabs will not be grouped

If the experiment is repeated, without the bottom empty tab (as described in step 1), the issue disappears.

**Comment by asamuzaK** [comment]
Confirmed.

**Comment by asamuzaK** [comment]
Reproduced once, but when I tried again, it did not reproduce.
We may need to verify the condition a little more.

**Comment by asamuzaK** [comment]
Maybe version dependent issue?

Good:
* 108.0a1
* 107.0b3

Bad:
* 106.0.1
* 102.4.0esr

**Comment by eugbyte** [comment]
I am using `v9.0.1` of the web extension, and Firefox `v106.0`

**Comment by eugbyte** [comment]
This is what I am experiencing
![ezgif-4-04d44f26ac](https://user-images.githubusercontent.com/20870423/197130825-f5714450-b78f-4ff5-b0b7-50a6c1e83dac.gif)

**Comment by asamuzaK** [comment]
I see that too on 106.0.1 and esr.

On the other hand, in Beta and Nightly, middle-click opened links are opened in the foreground with focus instead of being opened in the background.
This behavior looks like another bug in Beta and Nightly.

**Comment by eugbyte** [comment]
Tried Firefox beta, bug indeed disappeared

**Comment by asamuzaK** [comment]
About middle click.
It was expected behavior.
[Use mouse shortcuts to perform common tasks in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/mouse-shortcuts-perform-common-tasks#fgbg)

**Comment by asamuzaK** [comment]
I've found that this bug may or may not reproduce depending on your settings.
If you uncheck `When you open a link, image or media in a new tab, switch to it immediately`, issue reproduce.
If you check it, issue does not reproduce.

**Comment by asamuzaK** [comment]
As far as I have tested, this issue seems to be fixed and no regression.
Will release v9.0.2 shortly.

Thanks for your contribution.
