### ISSUE TITLE
When opening a new tab via right click in the side panel it opens a new tab in every open window

### ISSUE THREAD

**Issue by reneBrah** [asamuzaK/sidebarTabs#219]

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
While testing I noticed another bug #221
I will update the add-on once #221 is fixed.

**Comment by asamuzaK** [comment]
It will take some time to resolve #221, so I will release an updated version soon.

**Comment by reneBrah** [comment]
Awesome, thanks.
