### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by rayman89** [asamuzaK/sidebarTabs#22]
I think it would be great specially for users like us with a lot of open tabs to have a search bar at the top that filters the tabs so that we can easly find the tabs we want to open or do stuff like duplicate close mute etc to them.

**Comment by asamuzaK** [comment]
You can do that from the URL bar.
Add `%` at the end like `key %`.

See [Awesome Bar - Search your Firefox bookmarks, history and tabs from the address bar | Firefox Help](https://support.mozilla.org/en-US/kb/awesome-bar-search-firefox-bookmarks-history-tabs#w_changing-results-on-the-fly_2 "Awesome Bar - Search your Firefox bookmarks, history and tabs from the address bar | Firefox Help")

**Comment by rayman89** [comment]
Well its not just to jump to the tab if you implement doing stuff with multiple tabs for example you could search youtube then all the youtube tabs would be there and then you could mute them all or close them etc.

**Comment by asamuzaK** [comment]
How about using other add-ons for searching tabs?

[TabSearch](https://addons.mozilla.org/firefox/addon/tab_search/)
[Tab Search](https://addons.mozilla.org/firefox/addon/tab-search-smarter/)

**Comment by rayman89** [comment]
The issue would still remain the problem is not finding the tab but filtering them to be able to do stuff to those filtered tabs in bulk.  Also it's a lot better to be able to you one addon for tab managing that having to do 1 thing on this tab manager one other thing in this other and so on.

**Comment by asamuzaK** [comment]
> filtering them to be able to do stuff to those filtered tabs in bulk

This is out of purpose.
I'm not aiming this add-on to be all-in-one.

**Comment by rayman89** [comment]
I think you addon is really fitting to be THE tab manager addon it already has all the things needed plus tab grouping which is great.  It's just lacking the search function. There is no need to get it implemented ASAP it's ok if you make it just whenever but please consider it. I think a full featured tab manager addon is what users with big sessions are looking for the most after quantum.

**Comment by asamuzaK** [comment]
The purpose of this add-on is to
* emulate actual tabs and display them in the sidebar
* group tabs to improve visibility

Please understand that this feature request is completely different from what add-on is about to provide.
