### ISSUE TITLE
Color of tab group color bar changes when a new tab is added

### ISSUE THREAD

**Issue by eugbyte** [asamuzaK/sidebarTabs#222]
If there are 2 tab groups, the color of tab group color bar of the bottom tab group changes when a new tab is added to the top tab group

**Comment by asamuzaK** [comment]
It is designed that way.

The color of the group has no more meaning than to make it distinct from the adjacent tab groups.
There are four colors available, and the color is determined by the number of the tab group.

Note that tabs that are not grouped also belongs to a tab group, but color is not applied in this case.

A fairly simplified CSS is something like this:
```
group:nth-child(4n + 1) > tab {
  background-color: var(--tab-group-1);
}
group:nth-child(4n + 2) > tab {
  background-color: var(--tab-group-2);
}
group:nth-child(4n + 3) > tab {
  background-color: var(--tab-group-3);
}
group:nth-child(4n) > tab {
  background-color: var(--tab-group-4);
}
group:only-child > tab {
  background-color: none;
}
```

And tab groups results like this:
```
<group>
  <tab/> <!-- --tab-group-1 applied -->
  <tab/> <!-- --tab-group-1 applied -->
</group>
<group>
  <tab/> <!-- no color applied -->
</group>
<group>
  <tab/> <!-- --tab-group-3 applied -->
  <tab/> <!-- --tab-group-3 applied -->
</group>
<group>
  <tab/> <!-- --tab-group-4 applied -->
  <tab/> <!-- --tab-group-4 applied -->
</group>
<group>
  <tab/> <!-- --tab-group-1 applied -->
  <tab/> <!-- --tab-group-1 applied -->
</group>
```

**Comment by asamuzaK** [comment]
In other words, if the color of a tab group is fixed to the first color applied, groups of the same color may end up next to each other when the group is added or removed several times.

This should be avoided and is therefore the current implementation.
