### ISSUE TITLE
Custom theme is not working

### ISSUE THREAD

**Issue by eugbyte** [asamuzaK/sidebarTabs#226]
I am currently using Firefox `109.0b5 (64-bit)`. When I try to customize my own theme via the Custom theme option, e.g. changing the font color, it does not work.

However, directly changing the user stylesheet via `Apply user stylesheet` works

**Comment by asamuzaK** [comment]
Confirmed

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
Mozilla is attempting to change the default theme on Nightly (110.0a1) and there are regression bugs that have not yet been resolved.
Note that those changes are applied to the try build.
