### ISSUE TITLE
Rename "Init" to "Reset"

### ISSUE THREAD

**Issue by eugbyte** [asamuzaK/sidebarTabs#227]
Rename "Init" to "Reset" for better user experience

**Comment by asamuzaK** [comment]
The word `init` is used in two places.

* One is a button to initialize / reset the custom theme
* The other is a button to initialize / reset the sidebar itself and its description

Do you mean we should change both?

**Comment by asamuzaK** [comment]
If we do change it, in Japanese it will remain `初期化` (initialized).
@MasterKia How about in Farsi?

**Comment by eugbyte** [comment]
Yup, for EN, change both
