### ISSUE TITLE
Move tab to existing window

### ISSUE THREAD

**Issue by rayman89** [asamuzaK/sidebarTabs#23]
Would be possible to add a menu item to move tab(s) to an existing window? The name of the windows could be the name of their active tab to be able to differentiate them.

Also would be great if you could add the option too to be able to copy the url of the selected tabs in the case you implement a way to do actions to multiple tabs https://github.com/asamuzaK/sidebarTabs/issues/21 same to the ability to discard/suspend the selected tabs.

Thank you.

**Comment by asamuzaK** [comment]
Things needed to consider:

* How should it be displayed if the active tab in different windows refers to the same site?

**Comment by asamuzaK** [comment]
> Also would be great if you could add the option too to be able to copy the url of the selected tabs

This feature is out of purpose.

**Comment by rayman89** [comment]
I don't understand your points

if by "How should it be displayed if the active tab in different windows refers to the same site?"  you mean what would happen if the user have duplicated tabs in one/multiple windows and also they are at the same time the active tab? If  you were wondering that then that would be rare but if it happens then the user will notice that window's name depend on active tab and they can just change the active tab on the destination window to be able to differentiate the windows.

Drag and drop tabs to other windows doesn't need to be implemented IMO. Using "move to existent window" would suffice but if you wanna implement that how would you do it and why? 

"This feature is out of purpose." Means you don't find that feature useful? If that's the case then I want to tell you that I requested that because it's useful for when you want to share urls with other people or send a tab list to yourself to open them later on an other computer and you don't wanna use the tab sync feature that would do a lot more than just that.  Or if you were doing some research and want to keep the urls for web bibliography etc.  If by "This feature is out of purpose." you mean that the feature doesn't relate to "Move tab to existing window" and that I should open an other issue for that I would gladly do it.

**Comment by asamuzaK** [comment]
Suppose you have windowA, windowB, windowC.
And windowB's acitve tab is google.com and windowC's active tab is google.com.
And you want to move tab of windowA to windowC.

If add-on provides window's name only from the active tab title, context menu will be like this:

* Move Tab to Exsisting Window >
  (Sub menu)
  * Google
  * Google

Which is the windowC?

> Drag and drop tabs to other windows doesn't need to be implemented IMO.

Maybe drag and drop might be more straight foward for the user.
Maybe it's much simpler to implement (I have not tested yet).

Anyway, it is mainly a memo to myself about things to consider when implementing this function.

> "This feature is out of purpose." Means you don't find that feature useful?

Not for this add-on.
It should be done by other add-on for that purpose.

**Comment by rayman89** [comment]
Suppose you have windowA, windowB, windowC.
And windowB's acitve tab is google.com and windowC's active tab is google.com.

Go to the window you wanna send the tabs to (window C) and change the active tab to another to be able to identify on the menu which window is what. Having exactly the same url opened is not so common that it should be a deciding factor to whether implement the feature this way or not IMO.

**Comment by asamuzaK** [comment]
If such a thing is a solution, there is no point in implementing this feature.
You can copy the URL of the tab you want to move, move to other window, and paste it into the URL bar of the new tab.

**Comment by asamuzaK** [comment]
Maybe `titlePreface` can be used?
[windows.update() - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/update "windows.update() - Mozilla | MDN")

**Comment by asamuzaK** [comment]
There is an add-on to change window title [Crappy Firetitle – Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/crappy-firetitle/ "Crappy Firetitle – Add-ons for Firefox")
So, leave it to the user about window title conflict?

**Comment by asamuzaK** [comment]
Now you can drag and drop tabs to other existing window.

Caveats:
* Selection (highlight) will be canceled for some reason.
* Can not be grouped in other window even if you drag grouped tabs.
* Only droppable in sidebar.

**Comment by asamuzaK** [comment]
There are already some add-ons for this purpose. Try one of them?

* [All Tabs Helper](https://addons.mozilla.org/firefox/addon/all-tabs-helper/)
* [Tabby](https://addons.mozilla.org/firefox/addon/tabby-window-tab-manager/)
* [Tab Mover](https://addons.mozilla.org/firefox/addon/tab-mover/)
* [Other Window](https://addons.mozilla.org/firefox/addon/otherwindow/?src=search)
* [Move To Window](https://addons.mozilla.org/firefox/addon/move-to-window/?src=search)

**Comment by asamuzaK** [comment]
So I will not implement it for this add-on.
