### ISSUE TITLE
Doesn't show tabs; Pinned tabs needs scrollbar

### ISSUE THREAD

**Issue by neurodiverseEsoteric** [asamuzaK/sidebarTabs#234]
Addon only shows tabs that are opened after switching to it in the sidebar. With the exception of pinned tabs, but that's only the first 8 from the left end, and there's no means of scrolling...

**Comment by asamuzaK** [comment]
I don't understand what you're saying.
Please explain in more detail, for example by adding images.

**Comment by neurodiverseEsoteric** [comment]
I don't know how to explain it any better, but as you can see here: I have over 300 tabs currently open (most suspended using tabSuspender or inactive because I haven't clicked on them since (re-)launching the browser), but this addon doesn't even show all of the pinned tabs, thanks to having no scrollbar/scrolling feature for both pinned AND non-pinned tabs (if there were any showing, that is)...

![SidebarTabs_Screenshot_20221229_195129](https://user-images.githubusercontent.com/577091/210034463-169e8551-9fe6-490c-bc15-825a05002c8a.png)

**Comment by asamuzaK** [comment]
Do you have any extensions that hide tabs?
If so, temporarily disable those extensions and see if it works or not.
In general, this extension does not work well with those extensions that hide tabs.

**Comment by neurodiverseEsoteric** [comment]
FoxyTab has the option to hide tabs, but I never use it, and it's an essential addon for me. One of the other vertical tabs addons also has a hide feature, but that extension's disabled...

**Comment by asamuzaK** [comment]
Have you tried temporarily disabling FoxyTab?
If FoxyTab isn't the cause, try temporarily disabling other tab-related extensions and check.
If the cause or factor cannot be identified, I can't deal with it.

**Comment by neurodiverseEsoteric** [comment]
That's a lot of disruption for my actively in-use profile...

**Comment by asamuzaK** [comment]
Then please use another extension instead of this one.

**Comment by asamuzaK** [comment]
Reopened.

I found that you previously filed a similar issue #191.
Has the issue reappeared recently?
Or is it an issue that has been going on for a long time?

**Comment by neurodiverseEsoteric** [comment]
Wow, no recollection of that...But it's hard to say if it's reappeared or if that's been the case since I stopped using it and only retried it in the couple weeks...But I probably stopped using it because of this issue...

**Comment by asamuzaK** [comment]
Then please collect logs as before.

1. Disable Sidebar Tabs from about:addons
2. Open web console (Ctrl + Shift + J)
3. Enable multi process
4. Click the trash can icon and clear the web console output
5. Go back to about:addons and enable Sidebar Tabs
6. Copy logs and paste them here.

**Comment by neurodiverseEsoteric** [comment]
This is the output that the console returned right after enabling the addon:

```
15:27:23.857 Warning: attempting to write 7773 bytes to preference browser.uiCustomization.state. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.
15:27:38.692
```
...And this is what I got when I switched to it in the sidebar:
```
Some cookies are misusing the recommended “SameSite“ attribute 4
15:27:43.562
sendRemoveListener on closed conduit {ccc8cbaa-3c36-46d1-b0ae-d5e122755901}.274877933908 [ConduitsChild.jsm:112](resource://gre/modules/ConduitsChild.jsm)
15:27:43.563
Error: sendRemoveListener on closed conduit {ccc8cbaa-3c36-46d1-b0ae-d5e122755901}.274877933908 [ConduitsChild.jsm:112:13](resource://gre/modules/ConduitsChild.jsm)
15:27:43.592
Unknown property ‘-moz-context-properties’.  Declaration dropped. [sidebar.css:54:27](moz-extension://0928b3dd-6296-4dd4-9ed9-2ccd626c0fd7/css/sidebar.css)
15:27:43.666 Uncaught TypeError: Property 'handleEvent' is not callable.
15:27:43.900
Invalid contextual identity: firefox-container-24 [common.js:17:13](moz-extension://0928b3dd-6296-4dd4-9ed9-2ccd626c0fd7/mjs/common.js)
15:27:43.901 Uncaught (in promise) Error: Invalid contextual identity: firefox-container-24 undefined
```

**Comment by neurodiverseEsoteric** [comment]
![Screenshot_20221231_152936](https://user-images.githubusercontent.com/577091/210157653-0c2075c1-4bc5-4a06-9fc5-dbccae5640bd.png)

**Comment by asamuzaK** [comment]
To fix `Unknown property ‘-moz-context-properties’`:
Open `about:config` and set `svg.context-properties.content.enabled` to `true`.

And a [Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
See if issue is gone or not

**Comment by neurodiverseEsoteric** [comment]
Well, that does seem to fix the missing tabs issue, but I still can't 
scroll beyond the pinned tabs, and there's no collapse bar for them...

**Comment by asamuzaK** [comment]
Can not reproduce.
If the number of tabs increases, a scrollbar will appear.
The same is true for pinned tabs.
![screenshot](https://user-images.githubusercontent.com/6790339/210186746-59f0af51-8cf0-41af-89c7-aba52f2e0df6.png)

**Comment by asamuzaK** [comment]
Please collect logs and show them again.

**Comment by asamuzaK** [comment]
[2nd try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Improved handling of too many pinned tabs.
I'm not sure if this try build will solve your problem, but anyway give it a try.

Please let me know the result with a log.

**Comment by neurodiverseEsoteric** [comment]
Thanks. So, here's the logs for the 1st try build:
![Screenshot_20230103_121210](https://user-images.githubusercontent.com/577091/210434949-4c948a49-f22a-4808-8de9-9ce714e67f73.png)

And for the second try build:

![Screenshot_20230103_121549](https://user-images.githubusercontent.com/577091/210435027-18cd2b0b-e640-4a3a-b128-d6effc46792d.png)

The second build does allow me to scroll past all the pinned tabs, but there's little to no space to view more than two or three of the non-pinned tabs below...One feature request I have for all extensions like these, is the ability to resize the height of the pinned tabs section just like how one can resize the width of the sidebar (although for some reason firefox is imposing a maximum width which I wish I knew how to break)...


The scrollbars are also too thin...might be a 4K resolution issue, but could I prehaps change the min scrollbar width in some css file in the extension bundle, if not in a about:config parameter directly?

Sorry for the late replies but thanks for helping me out on this...

**Comment by asamuzaK** [comment]
> One feature request I have for all extensions like these, is the ability to resize the height of the pinned tabs section

* Open options page
* Enable `Apply user stylesheet` option and fill CSS like below
  ```
  .tab-container.pinned {
    max-height: 50vh;
  }
  ```

> The scrollbars are also too thin...

* Open options page
* Disable `Reduce scrollbar width` option

**Comment by asamuzaK** [comment]
What does `That` refer to?
Then what?
Your words always fall short of explanation.

If it's about scrollbar width, there's nothing we can do here.

**Comment by neurodiverseEsoteric** [comment]
`reduce scroll bar width` wasn't enabled

Why isn't it possible to do this:

```
.tab-container.pinned {
    resizable-on-mousedrag: true;
  }
```

**Comment by asamuzaK** [comment]
```
resize: overflow-y
```
can be specified.
However, this changes the `height` of the pinned tabs container, so there gonna be an extra white space when the pinned tabs are collapsed.

But if you disable tab grouping, this setting makes sense.

I'll add an extra CSS for that case then.

**Comment by neurodiverseEsoteric** [comment]
Okay Thanks. Sorry for not clarifying sooner...

**Comment by asamuzaK** [comment]
CSS alone can't keep the height on restart so I tried with ResizeObserver API.
But it's very very unstable.

Resizing occurs in various cases, not just when the user interacts with pinned tabs to resize.
For example, adding or removing pinned tabs will cause resizing, and changing the tab height will also cause resizing.
It would be very inefficient and costs too much to monitor and respond to them one by one.

Therefore, I concluded that this feature, add ability to resize by user's mouse action, is not worth implementing.

**Comment by asamuzaK** [comment]
Use user stylesheet and set max-height.
It can be achieved only with this CSS, except that you cannot handle with the mouse.

**Comment by neurodiverseEsoteric** [comment]
> But if you disable tab grouping, this setting makes sense.

I would like both enabled because sometimes I'm okay with a fast collapse for faster access to unpinned tabs, for which I'd still like to use the grouping features...Though another issue I should probably open up is that collapsing/expanding pinned tabs does bring me back to the previous pinned tab, but at the first tab to the left. Were that not the case, and restoring collapsed pinned tabs brought me to the last pinned tab I was on, I probably wouldn't have as much frustration with the scrolling/resizing of them...

**Comment by asamuzaK** [comment]
After some trial and error, I was finally able to implement it.

[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by neurodiverseEsoteric** [comment]
Okay, will test it once I'm back at my desktop...

**Comment by neurodiverseEsoteric** [comment]
Hmmm, still not getting a draggable pinned-tabs group...adding resize: block after max-height: 50vh, doesn't seem to have done anything, either...

**Comment by neurodiverseEsoteric** [comment]
Though the oddest behavior is happening, for some reason the non-pinned tabs section is doing some weird auto-scrolling every time I change tabs now...

**Comment by asamuzaK** [comment]
Show me the log and animation image

**Comment by asamuzaK** [comment]
Honestly, the fixes I've made so far aren't due to the bugs of extension itself.
It could be due to some other extension or some other cause, all I did was to make the extension more fail safe when the error occurs for such reasons.

I have been communicating with you for a long time, but nothing is clear at all.
And I'm tired of it.

If you really want to fix this issue, try with a clean profile first.
If there is a bug there, please report it.

If there are no bugs in the clean profile, but the bug occur in your regular profile, then there is a problem in your environment.
In that case, investigate the cause step by step on your own.

The most suspicious is the userChrome.css.
Add your userChrome.css to your clean profile.
If there is no bug, then try adding tab-related extensions one by one and see if the bug occurs.

**Comment by neurodiverseEsoteric** [comment]
Sorry I've been out of town so I couldn't do any further testing

**Comment by neurodiverseEsoteric** [comment]
Hey, I think it works now! I've been trying to troubleshoot on a profile I'm actively using, so switching to a new profile would take just as much time as moving to a new apartment across town. The active usage also makes removing cluttered output from the browser console a chore as well. However, I noticed an unusual warning from three out of the 276 tabs:
```
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!
```
This inspired me to look into anything in the config for stuff related to "async," "pan" and/or "scroll." There appears to be a zillion parameters with "scroll" in their label. I tweaked a few and somehow, not only has the annoying auto-scroll stopped happening, but the handle for resizing the pinned tabs finally appeared and functions as desired too!

Since I have no idea how that happened. Here's all the modified "scroll"-related parameters (some might have been modified by extensions on their own):

![Screenshot_20230120_134844-crop](https://user-images.githubusercontent.com/577091/213813437-5ea448cb-c43b-4fff-9caf-fdd456bfb87b.png)

5 out of 5 star extension. Thanks again, again, again; and sorry for all the annoyances...

**Comment by neurodiverseEsoteric** [comment]
~Hi again! So I finally discovered the true cause of the jump-scrolling effect...Seems to have to do with some jank that happens when the pinned tabs are too stretched out too long. Since I guess the browser starts getting confused about the (global?) scroll position when pinned tabs are taking about over a quarter of the total height of the browser window (within the sidebar).   Not sure if that's fixable; I'm just adding this note for the record...
