### ISSUE TITLE
Custom colors missing when using colorful firefox themes

### ISSUE THREAD

**Issue by Ameseattle** [asamuzaK/sidebarTabs#241]
I have used a sidebar custom theme to match my firefox theme for years.  Suddenly a couple of weeks ago the background and tabs switched to a light grey with white print.  It still works with the firefox pre-installed themes but I have vision problems and need a colorful theme to see. see attached:

Note that before a reboot the option screen changes and is not editable... after a reboot the option screen goes back to the custom values but the still do not work.  I have tried both a "custom theme reset" and a "sidebar tabs reset" but neither works.

Pic 1 - shows problem on options screen before firefox restart 
Pic 2 - sidebar custom theme with firefox basic theme (works correctly)
pic 3 - shows options screen after firefox restart
![pic 1](https://user-images.githubusercontent.com/62525904/211129205-a3fdd44e-42aa-4c31-a944-406b2f103cae.jpg)

![pic 2](https://user-images.githubusercontent.com/62525904/211129210-320b34f6-b302-4c03-a169-f23e1cd5d9dc.jpg)

![pic 3](https://user-images.githubusercontent.com/62525904/211129215-a73c5005-4206-44b0-b752-0654b34986b9.jpg)

**Comment by asamuzaK** [comment]
1. Apply the theme you always use (theme shown on 1st and 3rd)
2. Press the reset button of the custom theme
3. Try setting it again.

The theme you use seems to be using dark color scheme, but you set your custom colors in light theme.

**Comment by asamuzaK** [comment]
Forget my previous comment.
Confirmed the issue.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Thanks for your contribution.

**Comment by asamuzaK** [comment]
Released v10.1.0 with the fix.
It should be downloaded soon.

**Comment by asamuzaK** [comment]
@Ameseattle 
Has the issue been resolved in v10.1.0?
