### ISSUE TITLE
Extend tab groups context menu

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/sidebarTabs#25]
See #21

**Comment by asamuzaK** [comment]
Try build
[v0.28.0a3](https://github.com/asamuzaK/sidebarTabs/tree/master/dest "sidebarTabs/dest at master · asamuzaK/sidebarTabs")

**Comment by rayman89** [comment]
There are 2 issues. The first one is that when selecting "group selected tabs" it groups them but moves them all to the end of the tab list. The second issue is that you made all the tab managing features to apply to multiple tabs ONLY if they are on a group. This limits functionality. The best would be to just make the "Tab" commands apply to all the selected tabs independently of if they are on group or not.

**Comment by asamuzaK** [comment]
> The first one is that when selecting "group selected tabs" it groups them but moves them all to the end of the tab list.

That is the designed behavior.
Add-on does not have any info about *where* to put grouped tabs, so I decided to put them at the end.

> The second issue is that you made all the tab managing features to apply to multiple tabs ONLY if they are on a group.

That is what this issue is for.
This issue is about extending `Tab Group` context menu.

> apply to all the selected tabs independently of if they are on group or not.

That will require another menu item like

* `Tab`
* `Tab Group`
* `Selected Tabs`

But, at the moment, I am negative to add new menu `Selected Tabs`.

As I explained in another issue before, the aims of this extension are to emulate acutual tabs in the sidebar and to provide some grouping functions.
Managing tabs are out of scope of this add-on.

Implementing that feature will require a total re-design of handling tabs.

**Comment by rayman89** [comment]
I think people would expect the tab group to stay where the parent tab is now so if you have tabs  1 2 3 4 5 6 7 and select to group tabs 3 4 5 it would be 1 2 group 6 7. Re positioning the tabs of the group would be troublesome IMO.

I don't think there is a need to add any more menus many addons have the capacity to apply actions wither to a single or multiple tabs with 1 command. Just make it apply to all the selected tabs if selected tabs is 1 then only applies to that tab,

Vanilla firefox tab bar has tab managing capabilities and you are integrating group managing which is managing multiple tabs at once so applying commands to selected tabs should come as second nature.  People using this addon would expect that functionality.  I haven't look at your code but It should not require a total re design.

**Comment by asamuzaK** [comment]
How about context clicked tab to be the parent?

If the context clicked tab is within a group, it will be detatched from the group and create a new one next to that group.

Selected tabs: 2, 4, 6
```
1
[2]
[group]
3
[4]
5
[/group]
[6]
7
```

Case A: context click on 2
```
1
[group]
2
4
6
[/group]
[group]
3
5
[/group]
7
```

Case B: context click on 4 (grouped tab)
```
1
[group]
3
5
[/group]
[group]
4
2
6
[/group]
7
```

Case C: context click on 6
```
1
[group]
3
5
[/group]
[group]
6
2
4
[/group]
```

**Comment by asamuzaK** [comment]
Refactored.
After some testing, there was buggy behavior in caseC.
So I implemented top most selected tab to be the parent.

**Comment by asamuzaK** [comment]
Try build
[v0.28.0a4](https://github.com/asamuzaK/sidebarTabs/tree/master/dest "sidebarTabs/dest at master · asamuzaK/sidebarTabs")
