### ISSUE TITLE
Add an option to change the new tab function.

### ISSUE THREAD

**Issue by xmha97** [asamuzaK/sidebarTabs#251]
Hi, Please add the feature below:
- Opens a new tab after the active tab, instead of the last position.
![image](https://user-images.githubusercontent.com/23485114/221290560-efb3c362-564a-43ba-a02f-9a696eb659c4.png)

✔️ Expected Behavior
a new tab opened just after the currently active tab.

❌ Actual Behavior
a new tab is opened at the end of the row of tabs, but it's not intuitive.

Thanks.

**Comment by xmha97** [comment]
On about:config there is this option:
```
browser.tabs.insertAfterCurrent = true
```
Add an option to activate this flag in the extension settings, if possible.

**Comment by asamuzaK** [comment]
It's already following your browser settings.
I'm not going to add an option to change that setting.
There is already another extension for that purpose.
[New Tab Override](https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/)
