### ISSUE TITLE
The "Move tab to new window option" moves also a tab in another window

### ISSUE THREAD

**Issue by waltergallegog** [asamuzaK/sidebarTabs#253]
Version 10.2.3
I'm observing the following strange behavior with the "Move tab" -> "Move to new window" option.

Precondition:
 - Two Firefox windows open, each with say 10 tabs.
 - In window_1, I right click on the 5th tab and click in the option "Move tab" -> "Move to new window"
 - The tab is moved correctly to a new window, but the 5th tab of window_B is also moved to a new window.

The behavior is not systematic, but I have experienced at least 3 times.

Let me know if more details can be helpful
Thanks.

**Comment by asamuzaK** [comment]
Can't reproduce.

There seems to be a number of bugs related to tab movement in Bugzilla,
* [1400631 - browser.tabs.move() has unexpected behavior when moving tabs within the same window where tab positions are less than insertion point](https://bugzilla.mozilla.org/show_bug.cgi?id=1400631)
* [1714607 - Activating the tab menu moves current tab to new window](https://bugzilla.mozilla.org/show_bug.cgi?id=1714607)
* [1326664 - Selected tab occasionally moves to new window if I switch to another window while holdin left mouse button](https://bugzilla.mozilla.org/show_bug.cgi?id=1326664)
* [727420 - Tab tearing is too sensitive. Tabs frequently moved to new window accidentally.](https://bugzilla.mozilla.org/show_bug.cgi?id=727420)

Is the issue similar to any of these?

**Comment by waltergallegog** [comment]
It does not seem to be any of those issues.

I just reproduced it again. This time I had:
 - 3 windows opened. (windows A, B, C)
 - The windows were on different desktops (I'm using KDE desktop on Linux)
 - In all the 3 windows, the first tab was selected.
 - When I moved the first tab of windowA to a new window, I also got the first tab of windows B and window C in my current desktop, on separate windows each. 

I tried to reproduce it again, following the same procedure without success.

I will try disabling the sidebarTabs extension for a while to see if I can reproduce it with the default firefox tabs.

**Comment by asamuzaK** [comment]
I haven't been able to reproduce it myself, but found a possible bug in the code.

I'm about to upload a try build with the fix, but it contains a breaking change that only supports Firefox 112 and above.
It seems that addons-linter is not yet ready for that, so I can't upload a try build at the moment.
[Import Firefox 112 schema · Issue #4791 · mozilla/addons-linter](https://github.com/mozilla/addons-linter/issues/4791)
Please wait for a while.

**Comment by asamuzaK** [comment]
It was not because of the schema, linter doesn't accept version string like `112.0a1` anymore.
https://addons.mozilla.org/api/v5/applications/firefox/

**Comment by waltergallegog** [comment]
Thanks for the feedback and the quick possible fix, I'll wait for the build to test.
I have been testing in with the default firefox tabs and I haven't been able to reproduce it so far.

**Comment by asamuzaK** [comment]
I've found a STR

1. Create multiple windows (windowA, windowB) and create multiple tabs in each window.
2. In windowA, context click (right click) any tab (does not need to be active).
3. Do nothing with the context menu.
4. Switch to windowB and context click any tab.
5. Choose `Move Tab` > `Move to New Window`

**Comment by asamuzaK** [comment]
If there's no Beta or Nightly, then wait until next week for 112 to be released.
[Firefox Release Calendar](https://whattrainisitnow.com/calendar/)
