### ISSUE TITLE
Re arranging tabs

### ISSUE THREAD

**Issue by rayman89** [asamuzaK/sidebarTabs#26]
I noticed that re arranging tabs on tab sidebar does not get reflected on the actual tabs. Could you please implement it?

**Comment by asamuzaK** [comment]
What do you mean `re arranging tabs`?
Can you give me steps to reproduce, expected result and actual?

**Comment by rayman89** [comment]
Imagine you have tabs named A B C on the tab sidebar you move the tabs and put them like this C B A. That change only shows on te tab sidebar the firefox tabs remain A B C. It would be nice that if you change the order in the tab sidebar that it changes the order in firefox too.

**Comment by asamuzaK** [comment]
I know it occurs sometime, but I can not identify the condition to reproduce.
Anyway, I'm refactoring drag & drop handlers to fix #21

**Comment by asamuzaK** [comment]
Note:
If `Ctrl + click`  a tab, that tab will be selected.
You can select multiple tabs, and drag / drop them on other tab.

**Comment by rayman89** [comment]
The re arranging seems to be working properly now. I noticed though that if you want to move a whole group of tabs from one place to an other that's not possible (?) Using shift it moves the "parent tab" and groups it to the tab near where you dragged it. Using normal drag and drop it just takes parent tab out of the group and puts it near the other tab. Using control click to select the collapsed group's parent tab just moves the parent tab and finally using control click to select the whole tabs in the group and then moving them to an other position just breaks moves all the tabs but breaks the group.

**Comment by asamuzaK** [comment]
>  if you want to move a whole group of tabs from one place to an other that's not possible

That is not implemented.
Maybe some improvements when [Ability to handle tab with arrow keys · Issue #27 · asamuzaK/sidebarTabs](https://github.com/asamuzaK/sidebarTabs/issues/27 "Ability to handle tab with arrow keys · Issue #27 · asamuzaK/sidebarTabs") is fixed.

**Comment by asamuzaK** [comment]
Can I close this as fixed?

**Comment by rayman89** [comment]
If you don't plan to make groups able to move then yes. Close it.
