### ISSUE TITLE
Cannot open contextual menu

### ISSUE THREAD

**Issue by lenormf** [asamuzaK/sidebarTabs#260]
Hi,

I can’t find the way to open the context menu. I tried right-click on a tab/group, with combinations of modifiers.

Using Firefox v113.0.

Thanks!

**Comment by asamuzaK** [comment]
In more details please with a steps to reproduce.

**Comment by asamuzaK** [comment]
Cannot reproduce.
Please test again with a clean profile only with this extension installed.
And tell me about your OS.

**Comment by lenormf** [comment]
I rebooted and everything is working as expected now :)

It could have been a conflict with VerticalTabs Reloaded as well, which I disabled at some point.

Thanks!

**Comment by zkrx** [comment]
I've just installed your extension. I was able to reproduce by disabling the extension and enabling it back. After this, context menu showed but was empty (very small box). The only fix was to restart firefox. Disabling/enabling back the extension had no effect.

**Comment by asamuzaK** [comment]
Confirmed
