### ISSUE TITLE
[FEATURE] Move tabs group

### ISSUE THREAD

**Issue by lenormf** [asamuzaK/sidebarTabs#261]
Hi,

It’d be great to have a way to move an entire tabs group around.

Thanks!

**Comment by lenormf** [comment]
Thanks!

**Comment by asamuzaK** [comment]
On Mac, `Option (altKey) + DnD` seems to be a copy not move.
[Drag and drop items on Mac - Apple Support](https://support.apple.com/guide/mac-help/drag-and-drop-items-mh35852/mac)

Reopened.

**Comment by asamuzaK** [comment]
I forgot myself, but it was already implemented.
You can move all tabs in the group with `Shift + Ctrl + DnD`.

**Comment by lenormf** [comment]
Indeed, that works!
