### ISSUE TITLE
[BUG] Closing and re-opening a tab via `ctrl-T` doesn’t put the tab back into the original group

### ISSUE THREAD

**Issue by lenormf** [asamuzaK/sidebarTabs#264]
Hi,

Here is a small bug I found.

Reproducer:
- group two tabs together
- close one
- use the usual shortcut to re-open the closed tab (<kbd>shift</kbd><kbd>ctrl</kbd><kbd>t</kbd>)

Outcome: the two tabs are opened, ungrouped

Expected: the two tabs are grouped together, again.

Thanks!

**Comment by asamuzaK** [comment]
It's by design.
This extension only saves the latest group state.
Storing the past group state will use a lot of memory and disk.
