### ISSUE TITLE
Using `New Tab` on a grouped tab appends a tab to this group — using `New Tab` on an ungrouped tab opens a separate tab

### ISSUE THREAD

**Issue by lenormf** [asamuzaK/sidebarTabs#265]
Hi,

My main usecase is being able to create a new tab from a tab that is not grouped, and group the two automatically.

While playing around a bit, I found that the `New Tab` contextual action has a different side-effect depending on whether the selected tab is grouped.

Reproducers:
- on a grouped tab, select `New Tab`
- outcome: a new tab is appended to the current group

- on an ungrouped tab, select `New Tab`
- outcome: a new tab is created

Suggestion:
`New Tab` in the root of the contextual menu always creates an ungrouped tab.
`New Tab` in the `Tab Group` sub-menu appends a new tab to the current group, which is created if it doesn’t exist.

HTH!

**Comment by asamuzaK** [comment]
Originally there was no menu item for `New Tab` in the context menu, but Firefox added it at some point.
The current implementation of Firefox when selecting `New Tab` context menu is
* Open a new tab next to the current tab if `browser.tabs.insertManyAfterCurrent` is set to true
* For container tabs, open a new container tab

In line with this implementation, selecting `New Tab` from the tab group's context menu opens a new tab within the same group.

If you want to open a new tab unrelated to the group, please open a new tab from the "+" at the end of the tab list.

**Comment by lenormf** [comment]
Yes, and I would like an option to open a new tab in the same group as the currently ungrouped tab, could that be implemented?

**Comment by asamuzaK** [comment]
What do you mean?

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by lenormf** [comment]
The build works, thanks!

Is there any way to have that `New Tab` bound to a dedicated keyboard shortcut, to complement Firefox’ <kbd>ctrl</kbd><kbd>t</kbd>?
