### ISSUE TITLE
Ability to unload tabs

### ISSUE THREAD

**Issue by lenormf** [asamuzaK/sidebarTabs#267]
Hi,

It looks like the contextual menu doesn’t allow me to unload a single tab (`Unload Tab`), or all the ones selected (`Unload X Tabs`). Could this be made available?

Additionally, it’d be extra helpful if that option was also available for entire groups (`Tab Group`  → `Unload Tab Group`). I think the currently focused tab wouldn’t be unloaded, but that’s a predictable side effect.

Thanks!

**Comment by asamuzaK** [comment]
No plans to implement a context menu that Firefox does not have, except for tab groups.
Do that with other extension.

**Comment by lenormf** [comment]
Looks I was so used to `Vertical Tabs Reloaded`’s unload menu item that I thought it was built into Firefox!

For archiving’s sake, I’m now using [Tab Unloader](https://addons.mozilla.org/en-US/firefox/addon/tab-unloader-we/), and the contextual menu is there.

To unload an entire group, I select it with <kbd>shift</kbd>+<kbd>ctrl</kbd>+wiggle the cursor a bit, and unload them using the same action as above.
