### ISSUE TITLE
Easier way to select an entire tab group

### ISSUE THREAD

**Issue by lenormf** [asamuzaK/sidebarTabs#268]
Hi,

It’d be useful to be able to select an entire group easily.

Currently, one can use <kbd>shift</kbd>+<kbd>ctrl</kbd>+DnD to select a group, or select the first tab and <kbd>shift</kbd>+<kbd>ctrl</kbd>+click on the last one, but it could be made simpler.

How about <kbd>shift</kbd>+<kbd>ctrl</kbd>+double-click on any tab of the group to select the latter entirely?

**Comment by asamuzaK** [comment]
No.
Firefox has `browser.tabs.closeTabByDblclick` in `about:config`.
It will conflict with that config enabled.

**Comment by lenormf** [comment]
What about another keybinding?
