### ISSUE TITLE
Allow to open tab in 'no container tab'

### ISSUE THREAD

**Issue by sith-on-mars** [asamuzaK/sidebarTabs#269]
Currently, if I open a tab in the container, I couldn't choose to open the tab in 'no container tab' as in the native tab.

Step to reproduce:

1. Open a tab in the container.
2. Right click the tab.
3. Select 'Open in New Container Tab'.
4. Realising there is no 'No Container' option.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by sith-on-mars** [comment]
The test build worked! Many thanks for the quick fix ;)
