### ISSUE TITLE
[UX] Make Vertical Tabs behave like Brave / Edge

### ISSUE THREAD

**Issue by ShobuPrime** [asamuzaK/sidebarTabs#274]
I managed to make vertical tabs behave like [Brave Browser](https://brave.com/vertical-tabs/) / [Microsoft Edge](https://www.microsoft.com/en-us/edge/features/vertical-tabs?form=MT00D8) with the CSS in my repo: https://github.com/ShobuPrime/firefox-vertical-tabs

The native Firefox Sidebar is currently modified generically.

I would like to only edit the look of the sidebar for when the `sidebarTabs` option is selected -- instead of including `bookmarks, history, and synced tabs.`

I suspect I just need the appropriate "Sidebar Command" like:

```
[sidebarcommand*="sidebarTabs"]
```

but I don't know the correct identifier.
---
Feel free to incorporate the CSS as a future extension option -- if possible.

**Comment by asamuzaK** [comment]
The sidebar UI is set in Firefox itself, it cannot be changed from the extension.

[browser-sidebar.js - mozsearch](https://searchfox.org/mozilla-central/source/browser/base/content/browser-sidebar.js)
