### ISSUE TITLE
Permission needed

### ISSUE THREAD

**Issue by amnweb** [asamuzaK/sidebarTabs#282]
This is a bug or something else? And which permission is needed if I give them all?

![Screenshot 2024-02-05 000531](https://github.com/asamuzaK/sidebarTabs/assets/16545063/64750d11-9c59-4265-b36d-764024405bba)

![Screenshot 2024-02-05 000613](https://github.com/asamuzaK/sidebarTabs/assets/16545063/1ae8328d-e1d2-4da5-9dc1-3c7cb563a2fe)

![Screenshot 2024-02-05 000630](https://github.com/asamuzaK/sidebarTabs/assets/16545063/97907d68-6c0c-4e92-83a3-07b15cc6d7d3)

**Comment by asamuzaK** [comment]
It's upstream issue.
See [1851083 - Manifest V3 extensions with low privilege activeTab shows annoying blue dot for all websites](https://bugzilla.mozilla.org/show_bug.cgi?id=1851083)

**Comment by amnweb** [comment]
Yes, I found it just after opening this issue.
