### ISSUE TITLE
Adding a shorcut

### ISSUE THREAD

**Issue by xdanielc** [asamuzaK/sidebarTabs#285]
I've searched for ways to edit the shorcuts in firefoox but the best I could find was sme extension that doesn't have every option.

**Comment by asamuzaK** [comment]
Shortcut for what? Context menus?

**Comment by xdanielc** [comment]
I mean, I like to hide the tabs on the top, did it with css, but I want a shorcut for opening the tabs, There's a button for that, but no shorcut. Ctrl + B opens bookmarks, Ctrl + H history, but this "Tabs" menu doesn't have any shorcut 
![imagen](https://github.com/asamuzaK/sidebarTabs/assets/59803819/b3638240-3523-4ea9-9bac-ed0e538578ad)

**Comment by asamuzaK** [comment]
* Open `about:addons`, or `Ctrl+Shift+a`
* Click gear icon and click `Manage Extension Shortcuts`
* Set key combination for `Sidebar Tabs` -> `Toggle open/close state`

**Comment by asamuzaK** [comment]
Solved?

**Comment by asamuzaK** [comment]
See below for key combinations.
[Shortcut values](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#shortcut_values)

**Comment by xdanielc** [comment]
Wasn't aware FF had those options, worked perfecly!
