### ISSUE TITLE
Clash with Ctrl+H Bookmark

### ISSUE THREAD

**Issue by Kamrulhasan12345** [asamuzaK/sidebarTabs#288]
Hi there,
Whenever I press Ctrl+H, the bookmark starts showing up instead of my sidebar tabs from then on (even after restarting). If I press Ctrl+H again, then no sidebar comes when I hold my mous pointer on the left side or press Shift+ left or whatever. Maybe this has something to do with Firefox default sidebars, though I don't much. I had to reinstall sidebar tabs extensions every time I did this. Is there any good solution to this?

**Comment by asamuzaK** [comment]
See  #285
Does it help?

**Comment by Kamrulhasan12345** [comment]
Yeah, now this is fine!
