### ISSUE TITLE
Issues with light theme

### ISSUE THREAD

**Issue by Kamrulhasan12345** [asamuzaK/sidebarTabs#290]
Hi,
I am having some issues with light themes, don't know why, tried tinkering with css.light-dark, ui.systemUsesDarkTheme, browser.in-content.dark-mode, but no use (Lastly deleted their values, so all default now). 
![light_theme_issues](https://i.imgur.com/nJ56ka1.png)
I am using [Firefox Plus](https://github.com/amnweb/firefox-plus) userchrome theme.

**Comment by asamuzaK** [comment]
Ask [there](https://github.com/amnweb/firefox-plus/issues)
