### ISSUE TITLE
Addon Options to theming and transition customization

### ISSUE THREAD

**Issue by Kamrulhasan12345** [asamuzaK/sidebarTabs#291]
It would be great if we could reduce transition timing, or even if we could turn off transition from addon options. Furthermore, theming are would also be great.

**Comment by Kamrulhasan12345** [comment]
Like I want the sidebar to appear faster than currently it is. For the theming, I think an option to customize css on the addon options would be great, or even css classes for this extension could also help creating customized userchrome extensions for firefox.
Another thing I noticed when I snapped it with another app on the right, that I doesn't directly appear. I had to bring the history first and then had to use Sidebar Shortcut to bring it while in snapping mode in windows.

**Comment by asamuzaK** [comment]
> Like I want the sidebar to appear faster than currently it is.

The WebExtensions API is basically asynchronous.
It needs to wait for a response from the browser, there is no control on the extension side.

> For the theming, I think an option to customize css on the addon options would be great, or even somehow documenting css classes for the sidebar things could also help creating customized userchrome extensions for firefox.

Out of scope of this extension.

> Another thing I noticed when I snapped it with another app on the right, that I doesn't directly appear. I had to bring the history first and then had to use Sidebar Shortcut to bring it while in snapping mode in windows.

Sounds like a Windows or Firefox issue.

**Comment by Kamrulhasan12345** [comment]
Thanks a lot!
