### ISSUE TITLE
Dragging a tab and dropping it below last member of a group should not include it in the group

### ISSUE THREAD

**Issue by Montagnard11** [asamuzaK/sidebarTabs#293]
Dragging a tab and dropping it below last member of a group should not include it in the group

**Comment by asamuzaK** [comment]
On the other hand, someone may want to drop the tab at the end of the group.
There is no good way to determine whether user wants to separate the tab from the group and display it independently or move it to the end of the group.
There is a way to distinguish it by adding a modifier key and drop, but the `Shift` and `Ctrl` keys are already used.
`Alt+Drop` combinations are possible, but in Windows `Alt+Drop` is used to create shortcuts. It will confuse users if well-known combinations behave completely differently.
So, as of now, no good solution.

FYI, what you want to do can be done by selecting `Tab Group` -> `Detach Tab from Group` from the context menu.

**Comment by Montagnard11** [comment]
I understand and it's no big deal. I already used the "detach" command, 
but the real question is: do you really think more people want to 
include a tab in a group by dropping it below the last member of that 
group, or more people routinely reorganize their tabs and want to place 
any tab below a group without including it in the group?

One could argue that those who want to include it in the group can drop 
it on the head of the group then move it down, while those who don't 
have to open a submenu each time... In my short experience with your 
great add-on, it's "no grouping" nine times out of ten...

Ciao,

K.

**Comment by asamuzaK** [comment]
> do you really think more people want to include a tab in a group by dropping it below the last member of that group, or more people routinely reorganize their tabs and want to place any tab below a group without including it in the group?

I don't know.
All I can say is that this is probably the first time I've been asked to make this change.

I don't know the exact phrase in English, but I read in a book that, `In general, if there is one complaint, there are 24 other customers who have problems, and 6 of them are serious.`
So I'm sure you're not the only one with the problem.
However, at this point, I don't think it will be a large number.

Marking as `wont fix` for now.
If someone asks the same next time, let's consider the change of the default behavior.

**Comment by asamuzaK** [comment]
Reopened.
I realized there is another case where the behavior might need to be modified.

**Comment by asamuzaK** [comment]
[Try build](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

* On drop (mouse up)
  * The dragged tab(s) are independent of the dropped target tab.
* On drop (mouse up) with ShiftKey held
  * The dragged tab(s) will be grouped with the dropped target tab.

Please try it for a while to see if there are any regressions.
