### ISSUE TITLE
Abitily to toggle sidebar with a keyboard shortcut

### ISSUE THREAD

**Issue by FranciscoMurias** [asamuzaK/sidebarTabs#308]
Would be nice to be able to set a shortcut to open and close the sidebar

**Comment by asamuzaK** [comment]
See:
* [Manage extension shortcuts in Firefox | Firefox Help](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox)
* [Key combinations](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#key_combinations)

See also #285

**Comment by FranciscoMurias** [comment]
Thanks!
