### ISSUE TITLE
Ability to set "close" and "New Tab" Plus and Cross Icon Color

### ISSUE THREAD

**Issue by FranciscoMurias** [asamuzaK/sidebarTabs#309]
In dark themes the icons to close a tab or open a new tab are not very visible. Having an option to override their color to white or other colors would be useful
![image](https://github.com/user-attachments/assets/a230eafd-61d3-4f2a-9b6e-e326ff3f3d03)

**Comment by asamuzaK** [comment]
See https://github.com/asamuzaK/sidebarTabs?tab=readme-ov-file#aboutconfig
