### ISSUE TITLE
Dragging out a tab doesn't open a new browser window

### ISSUE THREAD

**Issue by FranciscoMurias** [asamuzaK/sidebarTabs#310]
The default Firefox behavior when you drag out a tab into an empty area of your desktop is to open that tab in a new window. This doesn't happen with the sidebarTabs. Would be nice if that functionality was added.

**Comment by FranciscoMurias** [comment]
Also dragging a tab (or set of tabs) into the bookmarks toolbar doesn't add those tabs to bookmarks as the default tab behaviour does

**Comment by asamuzaK** [comment]
Thank you for your contribution.

As a side note, Mozilla itself has started working on implementing sidebar tabs.
* Blog: [Firefox Sidebar and Vertical tabs: try them out in Nightly Firefox Labs 131 – Firefox Nightly News](https://blog.nightly.mozilla.org/2024/08/07/firefox-sidebar-and-vertical-tabs-try-them-out-in-nightly-firefox-labs-131/)
* Bugs: [1879923 - \[meta\] Sidebar work](https://bugzilla.mozilla.org/show_bug.cgi?id=1879923)

I believe that if you contribute there rather than here, I think you can further improve the quality and usability of Firefox.

**Comment by FranciscoMurias** [comment]
Thanks for this information. Hope the drag behavior fix isn't too difficult! 👍

**Comment by asamuzaK** [comment]
Brief test results:
* Drop native tab outside browser window
	* New window opens with native tab URL
	* Native tab is removed from original browser window tab strip
	* No effect with `Ctrl + dnd`, `Shift +dnd`
	  Native tab is removed from tab strip anyway
* Drop native tab to sidebar tab
	* Native tab is droppable but has no effect
	* Native tab remains in native tab strip
	* Results of dataTransfer (summary):
		* dropEffect: "move"
		* effectAllowed: "uninitialized"
		* types: Array [ "text/x-moz-text-internal" ]
	* No `text/plain` fallback in dataTransfer
* Drop native tab to bookmarks tool bar
	* Bookmark is created in bookmarks tool bar
	* Native tab remains in tab strip
	  Like similar to `dataTransfer.dropEffect === 'copy'`

* Drop dataTransfer.setData('text/plain', 'https://example.com'), e.g. select text `https://example.com` and drag and drop that selected text
	* Dropping on native tab, it opens that URL
	* Dropping on bookmarks toolbar, it bookmark that URL
	* Dropping on sidebar tab, it opens that URL

* Drop sidebar tab outside browser window
	* No effect
* Drop sidebar tab to native tab
	* Opens search result
	  It's because detaTransfer.type is `text/plain` with stringified json as value
* Drop sidebar tab to bookmark toolbar
	* Not droppable
	* Not sure what happens if tab will be removed or remains if detaTransfer.type with `text/plain` is dropped (not tested yet)

**Comment by asamuzaK** [comment]
After #311

* Drop sidebar tab outside browser window
  * Creates shortcut on desktop (unexpected)
* Drop sidebar tab to native tab
  * Duplicate (copy) tab (maybe unexpected but acceptable?)
* Drop sidebar tab to bookmark toolbar
  * Creates bookmark (expected)

**Comment by asamuzaK** [comment]
Ref [tabbrowser-tabs.js - mozsearch](https://searchfox.org/mozilla-central/rev/3366c3d24f1c3818df37ec0818833bf085e41a53/browser/base/content/tabbrowser-tabs.js#399)

```
// We must not set text/x-moz-url or text/plain data here,
// otherwise trying to detach the tab by dropping it on the desktop
// may result in an "internet shortcut"
dt.mozSetDataAt(
  "text/x-moz-text-internal",
  dtBrowser.currentURI.spec,
  i
);
```

`detach the tab by dropping it on the desktop may result in an "internet shortcut"`, this is the thing that is happening after #311.

From an extension's perspective, there's no way to know what's happening outside of the sidebar, e.g. no way to know if the tab you dropped is opened in a new window, or if the drag and drop was canceled etc.

I'll do some more research, but it seems like it's not easy to implement.

**Comment by asamuzaK** [comment]
Wrote about differences and caveats in [README](https://github.com/asamuzaK/sidebarTabs?tab=readme-ov-file#drag-and-drop).

**Comment by asamuzaK** [comment]
I don't think there is anything that the extension can do anymore.
If you have any suggestions that there is still a way to do, please reopen.
Thanks.
