### ISSUE TITLE
add explanation or rename about:config section in README

### ISSUE THREAD

**Issue by ssssamstrup** [asamuzaK/sidebarTabs#321]
In the readme.md there's a section called about:config
https://github.com/asamuzaK/sidebarTabs/?tab=readme-ov-file#aboutconfig

What does this setting change? 
Does it only improve dark-mode?

If it only improves Dark mode, it would be more clear to rename the section to »Improve dark mode icons«

If it improves other aspects of the plug-in please rename the section or add an explanation to the section describing what it improves. Changing about:config should only be done when the user knows exactly what it changes. ☺️

**Comment by asamuzaK** [comment]
Not just for dark themes.
Colors that theme specifies for icons are applied.

* Install a theme for example [Innovator – Balanced](https://addons.mozilla.org/en-US/firefox/addon/innovator-balanced/).
  Note that it specifies different color for active tab and inactive tab.
* Open https://example.com and some other tabs.
* Switch tabs and see the icon color of https://example.com

As you pointed out, the title is unclear.
PR welcome.
