### ISSUE TITLE
correct format for "Apply user stylesheet"

### ISSUE THREAD

**Issue by Ameseattle** [asamuzaK/sidebarTabs#323]
Hi,

I want to use the "override style" option to change the font and font size on the tabs but I can't figure out the correct css format.  Can you please supply me with a sample of the correct format?

Thanks

**Comment by asamuzaK** [comment]
https://github.com/asamuzaK/sidebarTabs/blob/master/src/css/sidebar.css#L49
`font` is only specified there.

Note that `--font-weight-active` is overwritten programmatically by the Option setting, so recommended to leave it as is.

**Comment by asamuzaK** [comment]
FYI, a new option to set the zoom level is now available.
I'm not sure if it will suit your needs, but give it a try.

* Open the option page of "Sidebar tab".
* Select "Custom Theme".
* In the "Zoom" option, set the zoom level with the slider.

**Comment by asamuzaK** [comment]
@Ameseattle Solved?

**Comment by asamuzaK** [comment]
No reaction.
Closing.
