### ISSUE TITLE
tab group option: open new tab inside the group at the end of the"group"

### ISSUE THREAD

**Issue by xerance** [asamuzaK/sidebarTabs#34]
Hello, would be neat with an option for new tab behaviors within the group. For example: if you open a new tabs inside a group, instead of opening it next to the tab within the group, it would be cool to have it be moved to the end of the group.

Like this: https://puu.sh/AvE2c/09dc16fec1.png

**Comment by asamuzaK** [comment]
How about adding an option for that?

**Comment by xerance** [comment]
Would love to, if I had any idea of how to do it :P 
Was just a suggestion, as it would be fairly useful for organizing and structuring your tabs.

**Comment by asamuzaK** [comment]
Try build [sidebarTabs/dest at master · asamuzaK/sidebarTabs](https://github.com/asamuzaK/sidebarTabs/tree/master/dest "sidebarTabs/dest at master · asamuzaK/sidebarTabs")

**Comment by asamuzaK** [comment]
I regard this issue as fixed.
Closing.

**Comment by xerance** [comment]
Thank you!
