### ISSUE TITLE
MinVersion

### ISSUE THREAD

**Issue by WonderMr** [asamuzaK/sidebarTabs#62]
"strict_min_version" in manifest.json is "64.0a1"
64.0a1 is a nightly build. Addon is not avaible for ordinal users.

**Comment by asamuzaK** [comment]
I know.
It use new API (menus.overrideContext) which is implemented in 64.

64 is now beta and will be released next month.
Ordinal users will get it then.

**Comment by WonderMr** [comment]
Thank you for your reply and thank you for this addon.
