### ISSUE TITLE
Losing groups on restart (was: Issues upon restart - cpu usage, losing groups and re-arranging tabs in sidebar)

### ISSUE THREAD

**Issue by xkvt** [asamuzaK/sidebarTabs#66]
Thank you for your work on this add-on, I really like the functionality, but I am struggling to overcome  some issues.
They all show up after restarting Firefox (usually after previous day normal exit).
I am using it on a portable Firefox install, starting usually with around 6-7 windows and 500 to 700 tabs.
After starting, Firefox keeps using a full cpu thread until I disable/enable Sidebar Tabs from Options (then it comes down to normal cpu usage).
While this one happens every time, the next 2 issues, although also showing up upon starting up, they do not happen every time (may not show up for 4 or 5 days).
After starting up, the groups I had created just disappear, sometimes all of them, every now and then, it keeps only one or two groups.
The other random strange acting is re-arranging some tabs in a window only on sidebar, like putting a dozen of them to the end. But if I look at the tab bar they are still in the right order (it only applies to the sidebar list).
As I believe this all might be caused by some conflict with other add-ons, I am attaching here the list of add-ons I am using for you to check if there are any incompatiblilities.
Please, do feel free to break down this issue in multiple ones if you find it to be a better approach.
Thanks in advance.
![2019-02-10 23_36_57-list](https://user-images.githubusercontent.com/47509360/52543224-d221ef00-2d9f-11e9-80d9-a3ae9a23eb37.gif)

**Comment by asamuzaK** [comment]
It seems better to split them into three issues.

The second issue seems to have conflicts with other add-ons, so let's treat it here.

For the first issue, high CPU usage, #67
For the third issue, re-arranging tabs order, #68

**Comment by asamuzaK** [comment]
There may be a conflict between the session saved by the sidebar tab and the session saved by other add-ons.

What happens if you disable session related or tab related add-ons?
Especially these three.
* SessionBoss
* FoxyTab
* Tabbie

**Comment by xkvt** [comment]
These automatic updates for add-ons are a real chore...
I found out that Session Boss was set to restore session on start and I had initially set it to "No action", so it might be losing its settings upon updating.
So, I am now testing if it might be from that weird action (Firefox restores the session and so was Session Boss trying to do).

**Comment by xkvt** [comment]
A moment ago, I had a remarkable event.
I had tried your new 1.2.1 on my test instance of the browser (a copy of the main one).
Upon installing it on the main instance, a window with groups lost all groups that were located after displaying tab (it was in the middle of the list).

**Comment by asamuzaK** [comment]
Any new information about this issue?

**Comment by asamuzaK** [comment]
There is no reply, so I will close the issue.
