### ISSUE TITLE
CPU usage sticks high even after all tabs are loaded on startup

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/sidebarTabs#67]
Split from #66

**Comment by asamuzaK** [comment]
@xkvt
Does the browser hang at startup when CPU usage is high?
Or, is it possible, for example, to scroll pages or to switch to another tab, even if CPU usage is high?

**Comment by xkvt** [comment]
It does not hang the browser but it might be just because I am running Firefox as multi-threaded and have a Xeon cpu with 4 hyperthreaded cores = 8.
It keeps one thread at max usage until I disable/enable Sidebar Tabs.

**Comment by asamuzaK** [comment]
Scripts are async, Promise based, so the browser should not hang.
However, the process of emulating tabs in the sidebar depends on the number of tabs, so in general, the more tabs you have, the higher usage of the CPU until the process ends.

> It keeps one thread at max usage until I disable/enable Sidebar Tabs.

Do you mean that CPU usage sticks high even after all sidebar tabs are loaded?

**Comment by xkvt** [comment]
> Do you mean that CPU usage sticks high even after all sidebar tabs are loaded?

Yes, it sticks high forever... or until I disable/enable the extension.

**Comment by xkvt** [comment]
I have to add that, when enabling, it just takes 4 ot 5 seconds to load the sidebar tabs.

**Comment by asamuzaK** [comment]
> Yes, it sticks high forever... or until I disable/enable the extension.

That is not an expected behavior.
I'll take a look at the startup process.
Give me some time to investigate.

**Comment by asamuzaK** [comment]
> I have to add that, when enabling, it just takes 4 ot 5 seconds to load the sidebar tabs.

One more question.
Is it the same (take 4 or 5 sec to load) if you close sidebar (click close button of the sidebar or click Sidebar Tabs icon in the toolbar) and open sidebar again?

**Comment by xkvt** [comment]
Yes it is the same, sometimes even less (2-3 seconds).

**Comment by asamuzaK** [comment]
OK, thanks.

**Comment by asamuzaK** [comment]
Try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/startup/dest)

Hope if high CPU usage forever would be fixed by this try.
I'm not sure though.

**Comment by xkvt** [comment]
Nope, unfortunately, still the same behaviour.

**Comment by asamuzaK** [comment]
Personal note:
Other possibilities is the racing condition issue.
That is, emulating tabs are running before all native tabs are loaded.

**Comment by asamuzaK** [comment]
New try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/startup/dest)

Added observer to make sure all tabs are loaded before emulating.

NOTE:
Handlers emulating tabs are also refactored.
Please also check that the tab order is correct (not regressed).

**Comment by xkvt** [comment]
Sorry, but still no improvement with this build...

**Comment by asamuzaK** [comment]
3rd try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/startup/dest)

Added change on startup of the background script.
Plus, to track down where the cause is, added some outputs to the console.
Please open the browser console from `Ctrl+Shift+J` and tell me the log of the output on startup, on closing/opening sidebar, and on disable/enable add-on.

The output should be something like:
```
background startup: [time]
background startup done: [time]
sidebar startup: [time]
localize HTML done: [time]
make connection done: [time]
port connected: [string]
set contextual IDs done: [time]
create context menu done: [time]
set main done: [time]
set theme done: [time]
tabs length: before: [length] after: [length]
emulate tabs done: [time]
restore tab groups done: [time]
restore tab containers done: [time]
restore highlighted tabs done: [time]
set session tab list done: [time]
get last closed tab done: [time]
sidebar startup done: [time]
```

Thanks for your help.

**Comment by xkvt** [comment]
Here are the logs you asked for:

[20190212_Startup.txt](https://github.com/asamuzaK/sidebarTabs/files/2855955/20190212_Startup.txt)
[20190212_CloseSidebar.txt](https://github.com/asamuzaK/sidebarTabs/files/2855956/20190212_CloseSidebar.txt)
[20190212_OpenSidebar.txt](https://github.com/asamuzaK/sidebarTabs/files/2855957/20190212_OpenSidebar.txt)
[20190212_DisableAddon.txt](https://github.com/asamuzaK/sidebarTabs/files/2855960/20190212_DisableAddon.txt)
[20190212_EnableAddon.txt](https://github.com/asamuzaK/sidebarTabs/files/2855961/20190212_EnableAddon.txt)

**Comment by asamuzaK** [comment]
Thanks, but are they the logs after you installed third try build?

**Comment by xkvt** [comment]
Yes, done with the 1.2.2a3 build.

**Comment by asamuzaK** [comment]
Hmm,
I can not understand why the output set by add-on is not logged.

In Startup.txt:
> Unchecked lastError value: Error: ID already exists:

Those IDs are menu item IDs of Sidebar Tabs.
But menu items are initialized on startup, so I have no idea why those errors are logged.

Anyway, I can not reproduce this issue on my side.
Open about 50+ tabs on startup, CPU usage increases but settles after loading.

**Comment by xkvt** [comment]
It is more evident with some 500+ tabs.
What I can try to do for you is to clone this test instance of the browser and then remove the maximum number of other add-ons and test again.

**Comment by xkvt** [comment]
It is more evident with some 500+ tabs.
What I can try to do for you is to clone this test instance of the browser and then remove the maximum number of other add-ons and test again.

**Comment by xkvt** [comment]
Removed all other add-ons except for Auto Tab Discard and re-tested with 1.2.2a3 build.
Also updated Firefox to latest 65.0.
Here are the new logs:

[20190212_Startup_2.txt](https://github.com/asamuzaK/sidebarTabs/files/2856399/20190212_Startup_2.txt)
[20190212_CloseSidebar_2.txt](https://github.com/asamuzaK/sidebarTabs/files/2856401/20190212_CloseSidebar_2.txt)
[20190212_OpenSidebar_2.txt](https://github.com/asamuzaK/sidebarTabs/files/2856402/20190212_OpenSidebar_2.txt)
[20190212_DisableAddon_2.txt](https://github.com/asamuzaK/sidebarTabs/files/2856405/20190212_DisableAddon_2.txt)
[20190212_EnableAddon_2.txt](https://github.com/asamuzaK/sidebarTabs/files/2856406/20190212_EnableAddon_2.txt)

**Comment by asamuzaK** [comment]
Maybe only errors and warnings are logged?
Press `Toggle filter bar` button and check if `logs` and `info` are enabled?

**Comment by xkvt** [comment]
Only the three last ones, CSS, XHR and Requests are not highlighted.

**Comment by asamuzaK** [comment]
It is strange why no logs are left.
This is my screenshot of disabling / enabling add-on.
![ss](https://user-images.githubusercontent.com/6790339/52648434-e2fe6c00-2f29-11e9-94c4-8b944ce03119.png)

**Comment by xkvt** [comment]
I also start by getting some similar output but not the "Event" info???
![image](https://user-images.githubusercontent.com/47509360/52666103-3a3e1580-2f05-11e9-8736-5f5c828c067e.png)

**Comment by asamuzaK** [comment]
4th try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/startup/dest)

Added runtime.lastError handler.
`Unchecked lastError value: Error: ID already exists: foo` on startup should be gone.

**Comment by xkvt** [comment]
I cloned the portable instance to a new one and started with a clean profile, with just Sidebar Tabs and Auto Tab Discard.

Installed this new 1.2.2a4 build, and here is the log from the browser console:

`STARTUP:


SidebarUI is undefined ext-sidebarAction.js:396

    isOpen chrome://browser/content/parent/ext-sidebarAction.js:396 isOpen chrome://browser/content/parent/ext-sidebarAction.js:456 isOpen self-hosted:974 result resource://gre/modules/ExtensionParent.jsm:947 withPendingBrowser resource://gre/modules/ExtensionParent.jsm:601 InterpretGeneratorResume self-hosted:1255 next self-hosted:1210 result resource://gre/modules/ExtensionParent.jsm:946 withTiming resource://gre/modules/ExtensionParent.jsm:913 InterpretGeneratorResume self-hosted:1255 next self-hosted:1210 call resource://gre/modules/ExtensionParent.jsm:945 InterpretGeneratorResume self-hosted:1255 next self-hosted:1210 

1550052932020	addons.webextension.{c2c003ee-bd69-42a2-b0e9-6f34222cb046}	WARN	Loading extension '{c2c003ee-bd69-42a2-b0e9-6f34222cb046}': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox” browser.xul
SidebarUI is undefined ext-sidebarAction.js:396

    isOpen chrome://browser/content/parent/ext-sidebarAction.js:396 isOpen chrome://browser/content/parent/ext-sidebarAction.js:456 isOpen self-hosted:974 result resource://gre/modules/ExtensionParent.jsm:947 withPendingBrowser resource://gre/modules/ExtensionParent.jsm:601 InterpretGeneratorResume self-hosted:1255 next self-hosted:1210 result resource://gre/modules/ExtensionParent.jsm:946 withTiming resource://gre/modules/ExtensionParent.jsm:913 InterpretGeneratorResume self-hosted:1255 next self-hosted:1210 call resource://gre/modules/ExtensionParent.jsm:945 InterpretGeneratorResume self-hosted:1255 next self-hosted:1210 

CLOSE/OPEN SIDEBAR: nothing logged...................................
	
DISABLE:
	
	TypeError: extension is undefined
receiveMessage@resource://gre/modules/ExtensionParent.jsm:356:5
_handleMessage/</<@resource://gre/modules/MessageChannel.jsm:922:19
_handleMessage/<@resource://gre/modules/MessageChannel.jsm:921:9
_handleMessage@resource://gre/modules/MessageChannel.jsm:919:7
receiveMessage/<@resource://gre/modules/MessageChannel.jsm:218:9
receiveMessage@resource://gre/modules/MessageChannel.jsm:211:5

ENABLE: nothing logged...................................`

**Comment by asamuzaK** [comment]
How about CPU usage?
Still sticking high after startup?

**Comment by xkvt** [comment]
Yep, still the same...

**Comment by asamuzaK** [comment]
Will CPU usage remain stuck if you do the following?

1. close sidebar
2. close browser
3. restart browser
4. open sidebar

**Comment by xkvt** [comment]
It does remain stuck when I do as you asked.
Only way to lower it still being disable/enable add-on.

**Comment by asamuzaK** [comment]
5th try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/startup/dest)

Added outputs to console again.
Please check Ctrl+Shift+J and tell me the result.

In addition, as an attempt for balance CPU usage, the script will be executed after 3 seconds.

**Comment by xkvt** [comment]
Result:
[20190213_1_2_2a5.txt](https://github.com/asamuzaK/sidebarTabs/files/2862384/20190213_1_2_2a5.txt)

**Comment by asamuzaK** [comment]
It seems like Sidebar Tabs is not being called at all on startup, or got stuck before it get executed?

There may still be some issue remaining on the add-on side, but maybe by some other reason, for example, profile is broken?

**Comment by xkvt** [comment]
As I mentioned before, I am now testing with a new profile, so that is not the culprit..

**Comment by asamuzaK** [comment]
For example, what happens if you reduce the number of tabs by half?

**Comment by xkvt** [comment]
The cpu usage % that sticks is nearly proportional to the number of tabs, for instance 600+ tabs 15%, 400+ tabs 10%, but after disabing enabling, the usage is very similar (1-2%).

**Comment by asamuzaK** [comment]
If it is possible, I want to compare the logs at startup in the following 4 cases?

· Restart the browser with Sidebar Tabs in sidebar
· Restart the browser with something other than Sidebar Tabs (eg bookmarks) in sidebar
· Restart the browser with Sidebar Tabs enabled but the sidebar is closed
· Restart the browser with Sidebar Tabs disabled and the sidebar is closed

**Comment by xkvt** [comment]
Here are the logs (all 4 in the same file):
[20190214_4.txt](https://github.com/asamuzaK/sidebarTabs/files/2866372/20190214_4.txt)

**Comment by asamuzaK** [comment]
Try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/startup/dest)

Refactored background scripts.
`SidebarUI is undefined` should be gone. (I hope...)

**Comment by xkvt** [comment]
OK, the message is gone.
The issue still remains....

**Comment by asamuzaK** [comment]
Are there any new errors in the log?
What is the difference between restart with Sidebar Tabs enabled, and restart with Sidebar Tabs disabled?

**Comment by asamuzaK** [comment]
> The cpu usage % that sticks is nearly proportional to the number of tabs, for instance 600+ tabs 15%, 400+ tabs 10%, but after disabing enabling, the usage is very similar (1-2%).

I could finally reproduce this situation.

It seems to me that memory is not garbage collected is a bug of Firefox itself, not the add-on side.
Of course, add-ons may have memory leak, though.

As a workaround to reduce memory usage, open `about:memory` and press `Minimize memory usage` button, instead of disabling/enabling the add-on from `about:addons` each time.

**Comment by asamuzaK** [comment]
Maybe this bug?
Ref [1523164 - Major memory leak in heap-unclassified](https://bugzilla.mozilla.org/show_bug.cgi?id=1523164)

**Comment by xkvt** [comment]
> What is the difference between restart with Sidebar Tabs enabled, and restart with Sidebar Tabs disabled?

When I start Firefox with Sidebar Tabs disabled, there is no sticking of the CPU usage.

> As a workaround to reduce memory usage, open `about:memory` and press `Minimize memory usage` button, instead of disabling/enabling the add-on from `about:addons` each time.

No luck with this one, still have to disable/enable.

> Maybe this bug?
Ref [1523164 - Major memory leak in heap-unclassified](https://bugzilla.mozilla.org/show_bug.cgi?id=1523164)

I think the bug has not showed up again after recent build as per the reporter.

**Comment by asamuzaK** [comment]
I am not familiar with memory management, but try and check the following?

Set `memory.dump_reports_on_oom` to `true` from `about:config`, then it will dump when running out-of-memory occurs at startup.
See [Debugging out-of-memory problems - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Emscripten/Techniques/Out_of_memory_error_reports)

Open `about:memory`.
`Measure and save` memory usage when CPU usage is high.
Disable/enable addon.
`Measure and save` memory usage again.
Load two files saved from `Load and diff`.

When I tried it in my environment, the value of `vsize-max-contiguous` of WebExtensions process was extremely reduced.
It may be because the heap allocation at startup was quite large due to the large number of tabs, and  for some reason, not garbage collected?

**Comment by xkvt** [comment]
Here is the result of that mem diff:
[diff_20190216_1140_memory_report_20190216_1143_memory_report_files.zip](https://github.com/asamuzaK/sidebarTabs/files/2871861/diff_20190216_1140_memory_report_20190216_1143_memory_report_files.zip)

**Comment by asamuzaK** [comment]
About memory management I am unlikely to be of your help.
I think that you should report to Bugzilla.

**Comment by asamuzaK** [comment]
Released v1.2.2 applying the fixes so far.

**Comment by asamuzaK** [comment]
Firefox seems to have improved the performance with 66.
The issue still remains?

**Comment by asamuzaK** [comment]
There is no reply, so I will close the issue.
