### ISSUE TITLE
Wrong tab order

### ISSUE THREAD

**Issue by asamuzaK** [asamuzaK/sidebarTabs#68]
Split from #66

**Comment by asamuzaK** [comment]
@xkvt
Try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/tab-order/dest)
See if issue is fixed or not.

Thanks

**Comment by xkvt** [comment]
Good work!
Upon installation, on the window where the problem was seen, misplaced tabs returned to their correct placement in the sidebar.
Thank you!

**Comment by asamuzaK** [comment]
Released v1.2.1 on AMO.
Should be downloaded soon.
