### ISSUE TITLE
New tab from pinned tab is pinned

### ISSUE THREAD

**Issue by mbaz** [asamuzaK/sidebarTabs#76]
I'm having a weird issue. In one particular window out of 8 I have opened, middle-clicking a link in a pinned tab results in a pinned tab. The context menu, however, shows a "pin tab" option, instead of "unpin". The tab has no close button. This animation shows the problem in progress:

![sidebartabs](https://user-images.githubusercontent.com/1630034/59052749-52082380-887f-11e9-8e6b-e0cb50d1ef58.gif)

This doesn't happen in other windows. I restarted Firefox and the same behavior continues.

I'm on Arch Linux, Firefox 67.0.1, and SidebarTabs 1.3.7.

**Comment by asamuzaK** [comment]
Please try the following and let me know the result.

* Unpin all pinned tabs
* Close sidebarTabs and reopen again
* Pin tabs again
* Middle-click the link of the pinned tab

**Comment by mbaz** [comment]
That fixed the problem; thanks!

One interesting thing is that I had to open and close SidebarTabs several times, as some tabs were showing the pinned icon, but the conext menu only offered the option to pin. After multiple tries and much right-clicking I was finally able to unpin all of them.

**Comment by asamuzaK** [comment]
You can select multiple tabs

* Click 1st pinned tab
* Shift + click last pinned tab
* Choose `Unpin Tabs`
