### ISSUE TITLE
[NOT AN ISSUE] Simple request

### ISSUE THREAD

**Issue by EstherMoellman** [asamuzaK/sidebarTabs#84]
Please, consider the possibility to add the following functions:

1) Automatically bookmarking all tabs by groups.

2) Closing/Opening all tabs when a different group is selected. In this case, all tabs in the selected group will appear, but only 1 tab will be loaded. 

Thank you in advance!

**Comment by asamuzaK** [comment]
>     1. Automatically bookmarking all tabs by groups.

Not planned. Out of purpose.

>     2. Closing/Opening all tabs when a different group is selected. In this case, all tabs in the selected group will appear, but only 1 tab will be loaded.

Filed #85

**Comment by asamuzaK** [comment]
Try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)
