### ISSUE TITLE
Allow grouping to be switched off (no tree/indentation/children)

### ISSUE THREAD

**Issue by grahamperrin** [asamuzaK/sidebarTabs#95]
Please, can you add a preference to allow use of the extension _without_ grouping? 

If it helps: https://github.com/piroor/treestyletab/issues/1070 removed a comparable feature from Tree Style Tab. 

Thanks

**Comment by asamuzaK** [comment]
Why don't you use other add-ons without trees and/or groupings?

Ref [Vertical tab bar without tree or grouping](https://github.com/piroor/treestyletab/blob/master/README.md#similar-projects)

**Comment by grahamperrin** [comment]
Thanks, I'm in the midst of drafting a post to Reddit, you might have answered my question!

**Comment by asamuzaK** [comment]
There are people who want to use only the vertical tab, so grouping should be able to opt-out.

Re-opened.

**Comment by asamuzaK** [comment]
Try build [sidebarTabs/dest at master](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

**Comment by grahamperrin** [comment]
At a glance: works for me. Thanks!
