### ISSUE TITLE
Context menu items greyed out

### ISSUE THREAD

**Issue by cppcooper** [asamuzaK/sidebarTabs#99]
The next context menu after highlighting two or more tabs has the option to `group selected` greyed out. This seemed to only be happening the first time I go to group tabs, and thereafter during the lifetime of firefox it was a nonissue. Upon further investigation however, it seems to happen for all functions the first time they should be applicable.

That is, after freshly launching firefox right clicking on tabs produces an entirely greyed out menu. If then, you go and select multiple tabs, for grouping them, the group selected option will then be greyed out. Subsequent context menus in any window, for (as far as I know) any tab as well, will not suffer this bug.

**Comment by asamuzaK** [comment]
Can't reproduce.

**Comment by cppcooper** [comment]
Firefox about:

72.0.1 (64-bit)
Mozilla Firefox for Arch Linux
archlinux - 1.0

**Comment by asamuzaK** [comment]
Maybe related? [1360278 - Want a preference to enable context menu on mouse up (for mouse gestures)](https://bugzilla.mozilla.org/show_bug.cgi?id=1360278)

**Comment by asamuzaK** [comment]
What happens if you switch `ui.context_menus.after_mouseup` pref from about:config?

**Comment by asamuzaK** [comment]
Ref for api [contextMenuShowEvent - Mozilla | MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/contextMenuShowEvent)

**Comment by cppcooper** [comment]
> What happens if you switch `ui.context_menus.after_mouseup` pref from about:config?

Yup, that resolves it. I guess you might as well close this, unless there is something you can and want to do about it in your code

**Comment by asamuzaK** [comment]
I'm planning to add an option for that feature.
Could you help testing?

**Comment by cppcooper** [comment]
Ya I can probably swing that.

**Comment by asamuzaK** [comment]
Thanks!
I'll contact you when I'm ready.

**Comment by asamuzaK** [comment]
Try build [sidebarTabs/dest](https://github.com/asamuzaK/sidebarTabs/tree/master/dest)

Please test the following

1. install try build
2. reset `ui.context_menus.after_mouseup` to default value (value should be `false`)
3. open options page of the extension
4. check `Allow extension to read browser settings` option
5. check `Show context menu on mouseup` option
6. see if context menu is not greyed out

**Comment by cppcooper** [comment]
I will try to get on this in the next several days

**Comment by asamuzaK** [comment]
Released v3.2.0 with this implementation.
Please reopen if you find any issues.
